package com.codeNext.resumateAI

object JobList {

    val jobList = mutableListOf(
        ".NET Developer",
        "3D Animator",
        "3D Artist",
        "3D Modeler",
        "Account Executive",
        "Account Manager",
        "Accountant",
        "Accounts Payable Clerk",
        "Accounts Receivable Clerk",
        "Acupuncturist",
        "Actuary",
        "Actor",
        "Actor (Stage)",
        "Actor (Voice)",
        "Administrative Assistant",
        "Administrative Officer (Government)",
        "Admissions Counselor",
        "Admissions Director",
        "AdonisJS",
        "Adult-Gerontology Nurse Practitioner (AGNP)",
        "Advanced EMT (AEMT)",
        "Advanced Practice Registered Nurse (APRN)",
        "Advertising Manager",
        "Aerospace Engineer",
        "Aesthetician / Esthetician",
        "Agricultural Consultant",
        "Agricultural Economist",
        "Agricultural Engineer",
        "Agricultural Equipment Technician",
        "Agricultural Inspector",
        "Agricultural Manager",
        "Agricultural Sales Representative",
        "Agricultural Scientist",
        "Agricultural Technician",
        "Agronomist",
        "AI Engineer",
        "AI Researcher",
        "Air Traffic Controller",
        "Aircraft Dispatcher",
        "Aircraft Mechanic",
        "Airline Pilot",
        "Airport Manager",
        "Allergist / Immunologist",
        "Analytical Chemist",
        "Anesthesiologist",
        "Angular Developer",
        "Animal Breeder",
        "Animal Caretaker",
        "Animal Caretaker (in medical/research settings)",
        "Animal Control Officer",
        "Animal Nutritionist",
        "Animal Scientist",
        "Animal Shelter Manager",
        "Animal Trainer",
        "Animator",
        "Announcer",
        "Anthropologist",
        "Anthropologist (Cultural, Social, Linguistic)",
        "Antiques Dealer",
        "Anxiety",
        "Apiarist (Beekeeper)",
        "Appliance Repair Technician",
        "Application Developer",
        "Application Security Engineer",
        "Appraiser (Art, Antiques, Collectibles)",
        "Aquaculturist",
        "Arbitrator",
        "Arborist",
        "Archaeologist",
        "Archaeologist (Field, Lab)",
        "Architect",
        "Architectural Drafter",
        "Architectural Technologist",
        "Archivist",
        "Archivist (Government, Corporate, Special Collections)",
        "Art Critic",
        "Art Director",
        "Art Handler",
        "Art Teacher",
        "Art Therapist",
        "Assembler",
        "Assessor",
        "Assistant Coach",
        "Assistant Manager (Retail)",
        "Assistant Professor",
        "Astrologer",
        "Astronomer",
        "Astrophysicist",
        "Athletic Trainer",
        "Atmospheric Scientist",
        "Attorney",
        "Auctioneer",
        "Audiologist",
        "Audio Engineer",
        "Auditor (Internal/External)",
        "Author",
        "Auto Body Technician",
        "AutoCAD",
        "Automation Engineer",
        "Automation Tester",
        "Automotive Engineer",
        "Automotive Glass Technician",
        "Automotive Mechanic",
        "Automotive Technician",
        "Aviation Manager",
        "AWS Solutions Architect",
        "Azure Cloud Engineer",
        "Babysitter",
        "Backend Developer",
        "Baker",
        "Bailiff",
        "Ballet Dancer",
        "Ballroom Dancer",
        "Band Leader",
        "Bank Teller",
        "Banquet Manager",
        "Bar Manager",
        "Barber",
        "Barge Operator",
        "Barista",
        "Bartender",
        "Beautician",
        "Bed & Breakfast Owner",
        "Behavioral Analyst (BCBA)",
        "Behavioral Therapist",
        "Bellhop",
        "Benefits Specialist",
        "Big Data Engineer",
        "Bioethicist",
        "Bioinformatician",
        "Biochemist",
        "Biologist",
        "Biomedical Engineer",
        "Biomedical Equipment Technician (BMET)",
        "Biomedical Scientist",
        "Biophysicist",
        "Biostatistician",
        "Biotechnology",
        "Blacksmith",
        "Blender",
        "Blockchain Developer",
        "Blogger",
        "Blood Bank Technologist / Specialist in Blood Banking (SBB)",
        "Boat Captain (Recreational/Charter)",
        "Boilermaker",
        "Booking Agent",
        "Booking Agent (Music/Entertainment)",
        "Bookkeeper",
        "Border Patrol Agent",
        "Botanist",
        "Brand Ambassador",
        "Brand Manager",
        "Bricklayer",
        "Broadcast Journalist",
        "Broadcast Technician",
        "Budget Analyst",
        "Building Inspector",
        "Bus Driver",
        "Bus Monitor",
        "Business Analyst",
        "Business Consultant",
        "Business Development Manager",
        "Business Development Representative",
        "Business Intelligence Analyst",
        "Business Intelligence Developer",
        "Business Owner",
        "Busser",
        "Butcher",
        "Butler",
        "Buyer",
        "C++ Developer",
        "Cabinet Maker",
        "CAD Designer",
        "CAD Technician",
        "Cafe Manager",
        "Call Center Agent",
        "Call Center Manager",
        "Call Center Representative",
        "Calligrapher",
        "Camera Operator",
        "Cardiac Care Nurse",
        "Cardiac Surgeon",
        "Cardiologist",
        "Cardiopulmonary Perfusionist",
        "Cardiovascular Technologist",
        "Caregiver",
        "Career Counselor",
        "Cargo Handler",
        "Carpenter",
        "Carpet Installer",
        "Cartographer",
        "Cartographer (Artistic/Historical)",
        "Case Management Nurse",
        "Case Manager",
        "Case Worker",
        "Cashier",
        "Casino Dealer / Croupier",
        "Casino Manager",
        "Casting Director",
        "Category Manager",
        "Caterer",
        "Catering Manager",
        "Cell Biologist",
        "Cement Mason",
        "Certified Nurse-Midwife (CNM)",
        "Certified Nursing Assistant (CNA)",
        "Certified Occupational Therapy Assistant (COTA)",
        "Certified Registered Nurse Anesthetist (CRNA)",
        "Chaplain (Healthcare)",
        "Chauffeur",
        "Chef",
        "Chef de Partie",
        "Chemical Engineer",
        "Chemist",
        "Chief Administrative Officer (CAO)",
        "Chief Compliance Officer (CCO)",
        "Chief Data Officer (CDO)",
        "Chief Diversity Officer (CDO)",
        "Chief Executive Officer (CEO)",
        "Chief Financial Officer (CFO)",
        "Chief Human Resources Officer (CHRO)",
        "Chief Information Officer (CIO)",
        "Chief Information Security Officer (CISO)",
        "Chief Marketing Officer (CMO)",
        "Chief Medical Information Officer (CMIO)",
        "Chief Nursing Informatics Officer (CNIO)",
        "Chief Operating Officer (COO)",
        "Chief People Officer (CPO)",
        "Chief Product Officer (CPO)",
        "Chief Revenue Officer (CRO)",
        "Chief Strategy Officer (CSO)",
        "Chief Sustainability Officer (CSO)",
        "Chief Technology Officer (CTO)",
        "Child Life Specialist",
        "Child Protective Services Worker",
        "Childcare Center Director",
        "Childcare Worker",
        "Chiropractor",
        "Choreographer",
        "Cinematographer",
        "Circus Performer (Acrobat, Clown, etc.)",
        "City Clerk",
        "City Manager",
        "Civil Engineer",
        "Civil Servant",
        "Claims Adjuster",
        "Classicist",
        "Clergy / Minister / Priest / Rabbi / Imam etc.",
        "Client Advisor",
        "Client Relationship Manager",
        "Climatologist",
        "Clinical Analyst",
        "Clinical Biochemist",
        "Clinical Director",
        "Clinical Documentation Specialist (CDS)",
        "Clinical Lab Scientist",
        "Clinical Manager / Department Director",
        "Clinical Nurse Specialist (CNS)",
        "Clinical Pharmacist",
        "Clinical Psychologist",
        "Clinical Research Associate (CRA)",
        "Clinical Research Coordinator",
        "Clinical Research Coordinator (CRC)",
        "Clinical Social Worker",
        "Cloud Architect",
        "Cloud Consultant",
        "Cloud Engineer",
        "Cloud Security Engineer",
        "Coach (Specify Sport/Level)",
        "College Counselor",
        "College Professor",
        "Colorist",
        "Colorectal Surgeon",
        "Comedian",
        "Commercial Manager",
        "Commercial Pilot",
        "Communications Director",
        "Communications Manager",
        "Communications Specialist",
        "Community Development Manager",
        "Community Health Worker",
        "Community Manager (Online/Social)",
        "Community Organizer",
        "Community Paramedic",
        "Compensation Analyst",
        "Compensation & Benefits Manager",
        "Compliance Attorney",
        "Compliance Manager",
        "Compliance Officer",
        "Composer",
        "Compounding Pharmacist",
        "Comptroller",
        "Computer Vision Engineer",
        "Concept Artist",
        "Concierge",
        "Concierge (Residential/Corporate)",
        "Concrete Finisher",
        "Conductor (Orchestra/Choir)",
        "Congressional Aide",
        "Conservator",
        "Conservation Officer",
        "Conservation Scientist",
        "Construction Engineer",
        "Construction Foreman",
        "Construction Laborer",
        "Construction Manager",
        "Construction Project Manager",
        "Construction Superintendent",
        "Construction Worker",
        "Consultant",
        "Consular Officer",
        "Content Creator",
        "Content Editor",
        "Content Manager",
        "Content Strategist",
        "Content Writer",
        "Contemporary Dancer",
        "Contract Attorney",
        "Contract Manager",
        "Controller",
        "Cook",
        "Copy Editor",
        "Copywriter",
        "Corporate Counsel",
        "Corporate Trainer",
        "Correctional Officer",
        "Cost Accountant",
        "Costume Designer",
        "Counseling Psychologist",
        "Counselor",
        "County Clerk",
        "Court Clerk",
        "Court Interpreter",
        "Court Reporter",
        "Crane Operator",
        "Creative Director",
        "Creative Strategist",
        "Credit Analyst",
        "Crime Analyst",
        "Criminal Investigator",
        "Criminologist",
        "Critic (Theater, Dance, Music)",
        "Critical Care Nurse (ICU Nurse)",
        "Critical Care Physician / Intensivist",
        "Crop Consultant",
        "Cruise Director",
        "Cryptographer (Non-security focus, e.g., historical)",
        "CT Technologist (Computed Tomography)",
        "Culinary Arts",
        "Curator",
        "Curriculum Developer",
        "Customer Care Representative",
        "Customer Service Assistant",
        "Customer Service Manager",
        "Customer Service Representative",
        "Customer Service Supervisor",
        "Customer Success Manager",
        "Customer Support (non-technical focus)",
        "Customs Broker",
        "Customs Officer",
        "Cyber Security Analyst",
        "Cyber Security Consultant",
        "Cyber Security Engineer",
        "Cybercrime Investigator",
        "Cytotechnologist",
        "Dairy Farmer",
        "Dance/Movement Therapist",
        "Dancer",
        "Data Analyst",
        "Data Architect",
        "Data Engineer",
        "Data Scientist",
        "Data Warehouse Engineer",
        "Database Administrator (DBA)",
        "Database Developer",
        "Dean",
        "Deep Learning Engineer",
        "Delivery Driver",
        "Demographer",
        "Dental Assistant",
        "Dental Hygienist",
        "Dental Laboratory Technician",
        "Dentist",
        "Dentist (DDS/DMD)",
        "Department Manager (Retail)",
        "Dermatologist",
        "Design Engineer",
        "Desktop Publisher",
        "Desktop Support Technician",
        "Detective",
        "Development Director (Non-Profit)",
        "DevOps Engineer",
        "Dialysis Nurse",
        "Dialysis Technician",
        "Dietetic Technician, Registered (DTR)",
        "Dietitian",
        "Dietitian / Registered Dietitian Nutritionist (RDN)",
        "Digital Artist",
        "Digital Marketing Manager",
        "Digital Marketing Specialist",
        "Diplomat",
        "Director",
        "Disc Jockey (DJ)",
        "Disease Intervention Specialist",
        "Dishwasher",
        "Dispatcher",
        "Dispatcher (Emergency)",
        "Distance Learning Coordinator",
        "District Manager (Retail)",
        "Diver",
        "Diversity & Inclusion Manager",
        "Dock Worker",
        "Doctor",
        "Doctor of Osteopathic Medicine (DO)",
        "Documentary Filmmaker",
        "Dog Breeder",
        "Dog Groomer",
        "Dog Trainer",
        "Dog Walker",
        "Dosimetrist (Medical)",
        "Drafter",
        "Dramaturg",
        "Driving Instructor",
        "Drone Pilot",
        "Dry Cleaner",
        "Drywall Finisher",
        "Drywall Installer",
        "E-commerce Manager",
        "E-commerce Specialist",
        "Ecologist",
        "Economic Development Officer",
        "Economist",
        "Editor",
        "Editorial Assistant",
        "Education Administrator",
        "Education Consultant",
        "EHR Specialist / Analyst (Electronic Health Record)",
        "Electrical Design Engineer",
        "Electrical Engineer",
        "Electrician",
        "Electrologist",
        "Electroneurodiagnostic Technologist (EEG Tech)",
        "Electronics Engineer",
        "Elementary School Teacher",
        "Elevator Mechanic",
        "Email Marketing Specialist",
        "Embalmer",
        "Embedded Systems Engineer",
        "Emergency Management Director",
        "Emergency Management Specialist",
        "Emergency Medical Dispatcher / 911 Operator",
        "Emergency Medical Technician (EMT)",
        "Emergency Medicine Physician",
        "Emergency Room Nurse (ER Nurse)",
        "Employee Relations Specialist",
        "Endocrinologist",
        "Endodontist",
        "Energy Engineer",
        "Entertainment Attorney",
        "Entomologist",
        "Entrepreneur",
        "Environmental Chemist",
        "Environmental Compliance Specialist",
        "Environmental Consultant",
        "Environmental Educator",
        "Environmental Engineer",
        "Environmental Health Specialist",
        "Environmental Planner",
        "Environmental Scientist",
        "Environmental Specialist",
        "Environmental Technician",
        "Epidemiologist",
        "Equal Opportunity Officer",
        "Equipment Manager (Sports Team)",
        "Equipment Operator",
        "Ergonomist",
        "ESL Teacher (English as a Second Language)",
        "Estimator",
        "Ethical Hacker",
        "Ethicist (Non-medical focus)",
        "Ethnobotanist",
        "Etiquette Consultant",
        "Event Coordinator",
        "Event Manager",
        "Event Planner",
        "Executive Assistant",
        "Executive Chef",
        "Executive Housekeeper",
        "Exercise Physiologist (Clinical)",
        "Explosives Technician / Blaster",
        "Extension Agent",
        "Fabricator",
        "Facilities Engineer",
        "Facilities Manager",
        "Family Physician",
        "Family Physician / General Practitioner (GP)",
        "Family Nurse Practitioner (FNP)",
        "Farm Advisor",
        "Farm Equipment Operator",
        "Farm Laborer",
        "Farm Manager",
        "Farm Worker",
        "Farmer",
        "Farrier (Horseshoeing)",
        "Fashion Designer",
        "Fashion Stylist",
        "Fast Food Worker",
        "FBI Agent",
        "Fence Erector",
        "Feng Shui Consultant",
        "Ferry Operator",
        "Festival Organizer",
        "Field Organizer",
        "Field Technician (Agriculture)",
        "Figure Skater (Professional)",
        "Film Critic",
        "Film Director",
        "Film Editor",
        "Film Producer",
        "Finance Director",
        "Finance Manager",
        "Financial Advisor",
        "Financial Analyst",
        "Financial Consultant",
        "Financial Controller",
        "Financial Planner",
        "Fire Inspector",
        "Fire Lookout",
        "Firefighter",
        "Firmware Engineer",
        "Fish & Game Warden",
        "Fisheries Biologist",
        "Fisherman",
        "Fitness Center Manager",
        "Fitness Instructor",
        "Fleet Manager",
        "Flight Attendant",
        "Flight Dispatcher",
        "Flight Instructor",
        "Flight Nurse / Transport Nurse",
        "Flight Paramedic",
        "Floor Layer",
        "Floor Manager",
        "Floral Designer",
        "Florist",
        "Flutter Developer",
        "Foley Artist",
        "Food & Beverage Director",
        "Food & Beverage Manager",
        "Food Critic",
        "Food Scientist",
        "Food Service Manager",
        "Food Stylist",
        "Foreign Service Officer",
        "Forensic Accountant",
        "Forensic Anthropologist",
        "Forensic Artist",
        "Forensic Chemist",
        "Forensic Nurse",
        "Forensic Psychologist",
        "Forensic Scientist",
        "Forensic Scientist (Medical Examiner, Toxicologist)",
        "Forensic Technician",
        "Forest Ranger",
        "Forester",
        "Forestry Technician",
        "Forklift Operator",
        "Founder",
        "Framer",
        "Franchise Owner",
        "Freight Agent",
        "Freight Broker",
        "Freight Forwarder",
        "Front Desk Agent",
        "Front Desk Clerk",
        "Front Desk Manager",
        "Frontend Developer",
        "Full Stack Developer",
        "Fund Manager",
        "Fundraiser",
        "Fundraising Manager",
        "Funeral Director",
        "Furniture Designer",
        "Furniture Finisher",
        "Futurist / Trend Forecaster",
        "Game Artist",
        "Game Designer",
        "Game Developer",
        "Game Programmer",
        "Gameplay Programmer",
        "Gaming Attendant (Casino)",
        "Gardener",
        "Gastroenterologist",
        "GCP Cloud Engineer",
        "Gemologist",
        "Genealogist",
        "General Contractor",
        "General Manager",
        "General Manager (Hotel/Restaurant)",
        "General Manager (Sports Team)",
        "General Practitioner (GP)",
        "General Surgeon",
        "Genetic Counselor",
        "Geneticist",
        "Geochemist",
        "Geographer",
        "Geographer (Human, Cultural)",
        "Geologist",
        "Geophysicist",
        "Geotechnical Engineer",
        "Geriatric Care Manager",
        "Geriatrician",
        "Gerontologist (Social)",
        "Ghostwriter",
        "GIS Analyst (Geographic Information Systems)",
        "GIS Specialist",
        "Glassblower",
        "Glazier",
        "Go Developer (Golang)",
        "Goldsmith",
        "Goldsmith/Silversmith",
        "Government Affairs Director",
        "Government Contractor",
        "Government Relations Manager",
        "Grant Writer",
        "Grant Writer (Medical/Scientific)",
        "Graphic Artist",
        "Graphic Designer",
        "Greeter",
        "Greenhouse Manager",
        "Grocery Clerk",
        "Groundskeeper",
        "Group Fitness Instructor",
        "Guidance Counselor",
        "Guest Relations Manager",
        "Guest Service Agent",
        "Gym Manager",
        "Habitat Restoration Specialist",
        "Hair Stylist",
        "Handwriting Analyst / Graphologist",
        "Handyman",
        "Hardware Design Engineer",
        "Hardware Engineer",
        "Head Cashier",
        "Head Teacher / Principal",
        "Health Coach",
        "Health Information Manager / Medical Records Administrator (RHIA)",
        "Health Information Technician (RHIT)",
        "Health Inspector",
        "Health Law Attorney",
        "Health Policy Analyst",
        "Health Program Manager",
        "Healthcare Administrator",
        "Healthcare Compliance Officer",
        "Healthcare Consultant",
        "Healthcare Data Analyst",
        "Healthcare Informatics Specialist",
        "Healthcare Manager / Administrator",
        "Heavy Equipment Operator",
        "Helicopter Pilot",
        "Help Desk Analyst",
        "Help Desk Technician",
        "Hematologist",
        "Heraldry Expert / Herald",
        "Herbalist",
        "Herd Manager",
        "High School Teacher",
        "Historian",
        "Historian (Academic, Public)",
        "Histotechnologist / Histologic Technician",
        "Holistic Health Practitioner",
        "Home Health Aide",
        "Home Health Aide (HHA)",
        "Home Health Nurse",
        "Home Organizer",
        "Horse Trainer",
        "Horticulturalist",
        "Horticulturist",
        "Hospice Nurse",
        "Hospital Administrator",
        "Hospital Administrator / CEO / Executive",
        "Hospital Pharmacist",
        "Hospitalist",
        "Host / Hostess",
        "Hotel Clerk",
        "Hotel Concierge",
        "Hotel Manager",
        "House Cleaner / Maid",
        "House Sitter",
        "Housekeeper",
        "Housekeeping Manager",
        "Housing Inspector",
        "Housing Manager",
        "HR Administrator",
        "HR Analyst",
        "HR Assistant",
        "HR Business Partner",
        "HR Coordinator",
        "HR Director",
        "HR Generalist",
        "HR Manager",
        "HR Specialist",
        "Human Resources Information Systems (HRIS) Analyst",
        "Human Services Worker",
        "HVAC Installer",
        "HVAC Technician",
        "Hydraulic Technician",
        "Hydrologist",
        "Hypnotherapist",
        "Ichthyologist",
        "Illusionist / Magician",
        "Illustrator",
        "Image Consultant",
        "Immigration Officer",
        "Immunologist",
        "Import/Export Specialist",
        "Improvisational Actor",
        "Incident Responder",
        "Indexer (Book/Database)",
        "Industrial Designer",
        "Industrial Engineer",
        "Infectious Disease Specialist",
        "Information Security Analyst",
        "Information Security Manager",
        "Infrastructure Engineer",
        "Inside Sales Representative",
        "Instructional Coordinator",
        "Instructional Designer",
        "Instructional Technologist",
        "Instrumentalist (specific instruments: Pianist, Violinist, Guitarist etc.)",
        "Insulation Worker",
        "Insurance Agent",
        "Insurance Underwriter",
        "Intelligence Analyst",
        "Intellectual Property Lawyer",
        "Interior Architect",
        "Interior Designer",
        "Internal Auditor",
        "International Business Manager",
        "International Relations Specialist",
        "Internist (Internal Medicine Physician)",
        "Interpreter",
        "Interventional Radiologist",
        "Inventer",
        "Inventory Manager",
        "Investigator",
        "Investment Analyst",
        "Investment Banker",
        "Investor Relations Manager",
        "iOS Developer",
        "iOS Engineer",
        "iOS UI/UX Designer",
        "IoT Developer",
        "Ironworker",
        "IT Auditor",
        "IT Consultant",
        "IT Coordinator",
        "IT Director",
        "IT Manager",
        "IT Project Manager",
        "IT Specialist",
        "IT Support Specialist",
        "Janitor",
        "Java Developer",
        "JavaScript Developer",
        "Jazz Dancer",
        "Jeweler",
        "Jeweler (Retail/Repair)",
        "Journalist",
        "Judge",
        "Kennel Attendant",
        "Key Account Manager",
        "Key Holder",
        "Kinesiotherapist",
        "Kitchen Manager",
        "Kitchen Porter",
        "Knife Sharpener",
        "Knowledge Manager",
        "Kotlin Developer",
        "Lab Assistant (Research)",
        "Lab Manager",
        "Lab Technician",
        "Labor Relations Specialist",
        "Labor and Delivery Nurse",
        "Lactation Consultant",
        "Landscape Architect",
        "Landscape Designer",
        "Landscape Manager",
        "Landscaper",
        "Language Instructor",
        "Law Clerk",
        "Law Professor",
        "Lawyer",
        "Layout Artist",
        "Leadership",
        "Learning & Development Coordinator",
        "Learning & Development Manager",
        "Leasing Consultant",
        "Leatherworker",
        "Lecturer",
        "Lecturer / Instructor (Health Sciences)",
        "Legal Advisor",
        "Legal Analyst",
        "Legal Assistant",
        "Legal Consultant",
        "Legal Secretary",
        "Legislative Analyst",
        "Legislative Assistant",
        "Level Designer",
        "Lexicographer",
        "Librarian",
        "Library Assistant",
        "Licensed Clinical Social Worker (LCSW)",
        "Licensed Mental Health Counselor (LMHC)",
        "Licensed Practical Nurse (LPN)",
        "Licensed Professional Counselor (LPC)",
        "Licensed Vocational Nurse (LVN)",
        "Life Coach",
        "Lighthouse Keeper",
        "Lighting Designer",
        "Lighting Technician (Theater/Concert)",
        "Limnologist",
        "Limousine Driver",
        "Line Cook",
        "Lineman",
        "Linguist",
        "Linux System Administrator",
        "Literacy Specialist",
        "Literary Agent",
        "Literary Critic",
        "Litigation Support Specialist",
        "Livestock Manager",
        "Lobbyist",
        "Lock Keeper (Canal)",
        "Locksmith",
        "Locomotive Engineer",
        "Logger",
        "Logistics Analyst",
        "Logistics Coordinator",
        "Logistics Manager",
        "Logistics Specialist",
        "Longshoreman",
        "Loss Prevention Agent",
        "Loss Prevention Manager",
        "Luxury Goods Advisor",
        "Lyricist",
        "Machine Learning Engineer",
        "Machine Operator",
        "Machinist",
        "Mail Carrier",
        "Maitre d'",
        "Makeup Artist",
        "Mammographer",
        "Managed Care Coordinator",
        "Management Analyst",
        "Management Consultant",
        "Manicurist / Pedicurist",
        "Manual Tester",
        "Manufacturing Engineer",
        "Marine Biologist",
        "Marine Engineer",
        "Marine Mechanic",
        "Marine Oiler",
        "Market Research Analyst",
        "Marketing Analyst",
        "Marketing Assistant",
        "Marketing Coordinator",
        "Marketing Director",
        "Marketing Manager",
        "Marketing Operations Manager",
        "Marketing Specialist",
        "Marriage and Family Therapist (MFT)",
        "Mason",
        "Massage Therapist",
        "Material Handler",
        "Materials Engineer",
        "Materials Scientist",
        "Mathematician",
        "Mayor",
        "Mechanic",
        "Mechanical Design Engineer",
        "Mechanical Engineer",
        "Mechatronics Engineer",
        "Media Buyer",
        "Media Planner",
        "Mediator",
        "Medical Assistant",
        "Medical Assistant (MA)",
        "Medical Biller",
        "Medical Billing & Coding",
        "Medical Coder",
        "Medical Coder (CPC, CCS)",
        "Medical Device Sales Representative",
        "Medical Director",
        "Medical Doctor (MD)",
        "Medical Examiner / Coroner",
        "Medical Geneticist",
        "Medical Illustrator",
        "Medical Illustrator / Animator",
        "Medical Interpreter / Translator",
        "Medical Laboratory Technician",
        "Medical Laboratory Technician (MLT)",
        "Medical Librarian",
        "Medical Marketing Manager",
        "Medical Office Manager",
        "Medical Officer",
        "Medical Physicist",
        "Medical Receptionist",
        "Medical Records Administrator (RHIA)",
        "Medical Researcher",
        "Medical Sales Representative",
        "Medical Science Liaison (MSL)",
        "Medical Scientist / Biomedical Researcher",
        "Medical Secretary",
        "Medical Secretary / Administrative Assistant",
        "Medical Social Worker",
        "Medical Technician",
        "Medical Technologist / Clinical Laboratory Scientist (CLS/MLS)",
        "Medical Transcriptionist",
        "Medical Writer",
        "Medical-Surgical Nurse",
        "Medium / Psychic",
        "Member Services Representative (Non-Profit)",
        "Mental Health Counselor",
        "Merchandise Planner",
        "Merchandiser",
        "Merchant Mariner",
        "Metal Fabricator",
        "Meteorite Hunter",
        "Meteorologist",
        "Microbiologist",
        "Microbiologist (Clinical)",
        "Microbrewer / Brewmaster",
        "Microservices Architecture",
        "Middle School Teacher",
        "Midwife",
        "Military Personnel (Various Ranks/Roles)",
        "Milliner (Hat Maker)",
        "Millwright",
        "Mineralogist",
        "Mining Engineer",
        "Mixologist",
        "Mobile App Developer",
        "Mobile Engineer",
        "Model (Fashion, Commercial)",
        "Model Maker (Architectural/Industrial)",
        "Molecular Biologist",
        "Molecular Biologist (Clinical)",
        "Mortgage Broker",
        "Mortician",
        "Motion Graphics Designer",
        "Motorcycle Courier",
        "Mover",
        "MRI Technologist",
        "Multimedia Artist",
        "Museum Curation",
        "Museum Director",
        "Museum Educator",
        "Museum Technician",
        "Music Producer",
        "Music Teacher",
        "Music Therapist",
        "Musical Director",
        "Musical Theatre Performer",
        "Musician",
        "Mycologist",
        "Mystery Shopper",
        "Mythologist",
        "Nail Technician",
        "Nanny",
        "Narrative Designer",
        "Naturalist",
        "Naturopathic Doctor (ND)",
        "Naval Architect",
        "Neonatal Intensive Care Unit (NICU) Nurse",
        "Neonatal Nurse Practitioner (NNP)",
        "Neonatologist",
        "Nephrologist",
        "Network Administrator",
        "Network Architect",
        "Network Engineer",
        "Network Security Engineer",
        "Network Technician",
        "Neurologist",
        "Neurosurgeon",
        "News Anchor",
        "News Producer",
        "News Reporter",
        "NLP Engineer (Natural Language Processing)",
        "Non-Profit Administrator",
        "Non-Profit Director",
        "Non-Profit Executive Director",
        "Nonprofit Management",
        "NoSQL Database Administrator",
        "Notary Public",
        "Nuclear Engineer",
        "Nuclear Medicine Physician",
        "Nuclear Medicine Technologist",
        "Nuclear Pharmacist",
        "Nurse (Registered Nurse - RN)",
        "Nurse Administrator / Manager",
        "Nurse Anesthetist",
        "Nurse Educator",
        "Nurse Manager",
        "Nurse Practitioner (NP)",
        "Nurse Researcher",
        "Nursing Informatics Specialist",
        "Nursery Manager",
        "Nutritionist",
        "Obstetrician / Gynecologist (OB/GYN)",
        "Occupational Health Nurse",
        "Occupational Medicine Physician",
        "Occupational Therapist",
        "Occupational Therapist (OT)",
        "Occupational Therapy Assistant",
        "Oceanographer",
        "Office Administrator",
        "Office Assistant",
        "Office Manager",
        "Ombudsman",
        "Oncologist",
        "Oncologist (Medical)",
        "Oncology Nurse",
        "Online Instructor",
        "Operating Engineer",
        "Operating Room Nurse (OR Nurse / Perioperative Nurse)",
        "Operations Analyst",
        "Operations Coordinator",
        "Operations Director",
        "Operations Manager",
        "Operations Supervisor",
        "Ophthalmic Assistant",
        "Ophthalmic Technician",
        "Ophthalmologist",
        "Ophthalmologist (Eye Surgeon)",
        "Optician",
        "Optometrist",
        "Optometrist (OD)",
        "Oracle Developer",
        "Oral and Maxillofacial Surgeon",
        "Oral Surgeon",
        "Orchestrator",
        "Organic Farmer",
        "Organizational Development Consultant",
        "Ornithologist",
        "Orthodontist",
        "Orthopedic Surgeon",
        "Orthoptist",
        "Ostomy Care",
        "Otolaryngologist (ENT)",
        "Otolaryngologist (ENT Specialist)",
        "Outreach Coordinator",
        "Outside Sales Representative",
        "Painter",
        "Painter (Artist)",
        "Paleographer",
        "Paleontologist",
        "Palliative Care Physician",
        "Paper Maker",
        "Paralegal",
        "Paramedic",
        "Parish Nurse",
        "Park Manager",
        "Park Naturalist",
        "Park Ranger",
        "Parking Attendant",
        "Parole Officer",
        "Partner",
        "Party Planner",
        "Pastry Chef",
        "Patent Attorney",
        "Pathologist",
        "Pathologist Assistant (PA)",
        "Patient Advocate / Patient Navigator",
        "Patient Financial Services Manager",
        "Patient Registrar / Admitting Clerk",
        "Pattern Maker",
        "Pawnbroker",
        "Payroll Manager",
        "Payroll Specialist",
        "Pediatric Dentist (Pedodontist)",
        "Pediatric Nurse",
        "Pediatric Nurse Practitioner (PNP)",
        "Pediatric Surgeon",
        "Pediatrician",
        "Pedicab Driver",
        "Penetration Tester",
        "Performance Artist",
        "Performance Management Specialist",
        "Perfumer",
        "Periodontist",
        "Permit Technician",
        "Personal Assistant",
        "Personal Assistant (High Net Worth/Celebrity)",
        "Personal Banker",
        "Personal Care Aide (PCA)",
        "Personal Concierge",
        "Personal Fitness Trainer",
        "Personal Shopper",
        "Pest Control Advisor",
        "Pest Control Technician",
        "PET Technologist (Positron Emission Tomography)",
        "Pet Groomer",
        "Pet Sitter",
        "Petroleum Engineer",
        "Pharmaceutical Sales Representative",
        "Pharmacist",
        "Pharmacologist",
        "Pharmacy Technician",
        "Philatelist (Stamp Collector/Dealer)",
        "Philologist",
        "Philosopher",
        "Phlebotomist",
        "Photo Editor",
        "Photographer",
        "Photojournalist",
        "PHP Developer",
        "Physiatrist (Physical Medicine & Rehabilitation)",
        "Physical Education Teacher",
        "Physical Therapist",
        "Physical Therapist (PT)",
        "Physical Therapy Assistant",
        "Physical Therapy Assistant (PTA)",
        "Physician",
        "Physician Assistant (PA)",
        "Physicist",
        "Piano Technician",
        "Piano Tuner",
        "Pilates Instructor",
        "Pilot",
        "Pipefitter",
        "Pipeline Operator",
        "Planning Technician",
        "Plant Breeder",
        "Plant Scientist",
        "Plasterer",
        "Plastic Surgeon",
        "Platform Engineer",
        "Playwright",
        "Plumber",
        "Pneumatic Technician",
        "Podcaster",
        "Podcast Host",
        "Podiatrist",
        "Poet",
        "Police Officer",
        "Policy Advisor",
        "Policy Analyst",
        "Political Campaign Manager",
        "Political Consultant",
        "Political Cartoonist",
        "Political Scientist",
        "Polymer Scientist",
        "Polysomnographic Technologist (Sleep Tech)",
        "Port Manager",
        "Porter",
        "Post-Anesthesia Care Unit (PACU) Nurse",
        "Postdoctoral Researcher",
        "Postal Worker",
        "Potter / Ceramist",
        "Poultry Farmer",
        "Power Plant Operator",
        "PPC Specialist (Pay-Per-Click)",
        "Practice Manager",
        "Precision Instrument Maker",
        "Prep Cook",
        "Preschool Teacher",
        "Preventive Medicine Specialist",
        "Primatologist",
        "Principal",
        "Principal Investigator (PI)",
        "Printmaker",
        "Private Investigator",
        "Probation Officer",
        "Process Engineer",
        "Procurement Manager",
        "Procurement Specialist",
        "Produce Manager",
        "Producer (Film/TV/Radio)",
        "Product Demonstrator",
        "Product Design Engineer",
        "Product Manager",
        "Product Marketing Manager",
        "Product Owner",
        "Production Artist",
        "Production Assistant",
        "Production Coordinator",
        "Production Designer",
        "Production Manager",
        "Production Worker",
        "Professional Gambler",
        "Professional Organizer",
        "Professional Scout (Sports)",
        "Professor",
        "Professor (Medical, Nursing, Health Sciences)",
        "Program Assistant (Non-Profit)",
        "Program Coordinator",
        "Program Director",
        "Program Manager",
        "Program Manager (Non-Profit)",
        "Program Officer (Non-Profit)",
        "Project Administrator",
        "Project Analyst",
        "Project Architect",
        "Project Coordinator",
        "Project Engineer",
        "Project Manager",
        "Proofreader",
        "Prop Master",
        "Property Manager",
        "Prosthetist / Orthotist",
        "Prosthodontist",
        "Prosecutor",
        "Provost",
        "Psychiatric Mental Health Nurse Practitioner (PMHNP)",
        "Psychiatrist",
        "Psychologist",
        "Public Administrator",
        "Public Affairs Specialist",
        "Public Defender",
        "Public Health Dentist",
        "Public Health Educator / Health Promotion Specialist",
        "Public Health Nurse",
        "Public Health Official",
        "Public Information Officer",
        "Public Relations Manager",
        "Public Relations Specialist",
        "Public Speaking",
        "Public Works Director",
        "Publisher",
        "Pulmonologist",
        "Puppeteer",
        "Purchasing Agent",
        "Purchasing Manager",
        "Python Developer",
        "QA Analyst (Quality Assurance)",
        "QA Engineer (Quality Assurance)",
        "QA Lead (Quality Assurance)",
        "QA Manager (Quality Assurance)",
        "Quality Control",
        "Quality Engineer",
        "Quality Improvement Coordinator",
        "Quantitative Analyst ('Quant')",
        "Race Car Driver",
        "Radiation Oncologist",
        "Radiation Therapist",
        "Radio Host",
        "Radio Producer",
        "Radiographer",
        "Radiologic Technologist",
        "Radiologic Technologist (Rad Tech / X-ray Tech)",
        "Radiologist",
        "Radiologist (Diagnostic)",
        "Railroad Conductor",
        "Railroad Engineer",
        "Rancher",
        "React Developer",
        "React Native Developer",
        "Real Estate Agent",
        "Real Estate Appraiser",
        "Real Estate Broker",
        "Receptionist",
        "Recording Engineer",
        "Recreation Leader",
        "Recreational Therapist",
        "Recruiter",
        "Recruitment Coordinator",
        "Recruitment Manager",
        "Recruitment Specialist",
        "Recycling Coordinator",
        "Referee / Umpire / Sports Official",
        "Regional Manager",
        "Registrar",
        "Registered Dietitian (RD)",
        "Registered Nurse (RN)",
        "Regulatory Affairs Specialist",
        "Reiki Practitioner",
        "Relationship Banker",
        "Relationship Coach",
        "Relationship Manager",
        "Release Engineer",
        "Religious Scholar / Theologian",
        "Remote Sensing Scientist",
        "Reporter",
        "Reproductive Endocrinologist",
        "Research Analyst",
        "Research Assistant",
        "Research Assistant (Medical)",
        "Research Associate",
        "Research Director",
        "Research Scientist",
        "Researcher",
        "Reservation Agent",
        "Respiratory Therapist",
        "Respiratory Therapist (RT)",
        "Restaurant General Manager",
        "Restaurant Manager",
        "Resume Writer",
        "Retail Associate",
        "Retail Banker",
        "Retail Buyer",
        "Retail Manager",
        "Retail Merchandiser",
        "Retail Pharmacist",
        "Retail Sales Associate",
        "Retail Sales Consultant",
        "Retail Supervisor",
        "Revenue Cycle Manager",
        "Reverse Engineering",
        "Rheumatologist",
        "Rigger",
        "Risk Analyst",
        "Risk Manager",
        "Risk Manager (Healthcare)",
        "Road Manager / Tour Manager",
        "Robotics Engineer",
        "Roofer",
        "Room Attendant",
        "Route Driver",
        "Ruby on Rails Developer",
        "Rust Developer",
        "Saddler / Harness Maker",
        "Safe Cracker / Safecracker Technician",
        "Safety Engineer",
        "Sailor",
        "Sales Analyst",
        "Sales Assistant",
        "Sales Associate",
        "Sales Clerk",
        "Sales Consultant",
        "Sales Coordinator",
        "Sales Director",
        "Sales Engineer",
        "Sales Floor Associate",
        "Sales Manager",
        "Sales Operations Manager",
        "Sales Representative",
        "Salesforce Administrator",
        "Salesforce Developer",
        "Sanitation Worker",
        "SAP",
        "Scala Developer",
        "Scaffolder",
        "Scheduler",
        "School Administrator",
        "School Counselor",
        "School Librarian",
        "School Nurse",
        "School Principal",
        "School Psychologist",
        "Science Teacher",
        "Scientific Glassblower",
        "Scientific Writer",
        "Screenwriter",
        "Scrum Master",
        "Sculptor",
        "Security Architect",
        "Security Consultant",
        "Security Director",
        "Security Guard",
        "Security Manager",
        "Security Officer",
        "Security Operations Center (SOC) Analyst",
        "Seismologist",
        "SEM Specialist (Search Engine Marketing)",
        "SEO Manager",
        "SEO Specialist (Search Engine Optimization)",
        "Server",
        "Session Musician",
        "Set Decorator",
        "Set Designer",
        "SharePoint Developer",
        "Sheet Metal Worker",
        "Sheriff",
        "Shift Lead",
        "Shift Manager",
        "Shift Supervisor",
        "Ship Captain",
        "Ship Engineer",
        "Ship Pilot",
        "Shipfitter",
        "Shipping and Receiving Clerk",
        "Shoe Shiner",
        "Shopper",
        "Short Order Cook",
        "Sign Language Interpreter",
        "Sign Painter",
        "Singer",
        "Site Reliability Engineer (SRE)",
        "Ski Instructor",
        "Ski Patrol",
        "Skincare Specialist",
        "Sleep Medicine Specialist",
        "Small Engine Mechanic",
        "Smart Contract Developer",
        "Social Media Coordinator",
        "Social Media Manager",
        "Social Media Specialist",
        "Social Secretary",
        "Social Services Director",
        "Social Worker",
        "Social Worker (Medical/Healthcare)",
        "Sociologist",
        "Software Architect",
        "Software Developer",
        "Software Engineer",
        "Software Engineering Manager",
        "Software Tester",
        "Soil Conservationist",
        "Soil Scientist",
        "Solar Energy Engineer",
        "Solar Panel Installer",
        "Solidity Developer",
        "Solutions Architect",
        "Sommelier",
        "Sommelier (Restaurant/Retail)",
        "Sonographer",
        "Sound Designer",
        "Sound Editor",
        "Sound Engineer",
        "Sound Mixer",
        "Sound Technician (Live)",
        "Sourcing Specialist",
        "Sous Chef",
        "Space Scientist",
        "Spa Attendant",
        "Spa Manager",
        "Spa Therapist",
        "Special Education Teacher",
        "Speech Language Pathologist",
        "Speech Therapist",
        "Speechwriter",
        "Spoken Word Artist",
        "Sports Agent",
        "Sports Analyst / Commentator",
        "Sports Broadcaster",
        "Sports Information Director",
        "Sports Journalist",
        "Sports Marketing Manager",
        "Sports Medicine Physician",
        "Sports Photographer",
        "Sports Psychologist (Performance focus)",
        "Sports Therapist",
        "Sprinkler Fitter",
        "SQL Developer",
        "Stable Hand",
        "Staff Accountant",
        "Stage Manager",
        "Stained Glass Artist",
        "State Park Ranger",
        "State Trooper",
        "Station Agent (Train/Bus)",
        "Statistician",
        "Steamfitter",
        "Sterile Processing Technician",
        "Stock Clerk",
        "Stockbroker",
        "Stocker",
        "Stonemason",
        "Store Clerk",
        "Store Detective",
        "Store Manager",
        "Storm Chaser",
        "Story Artist",
        "Storyboard Artist",
        "Strategic Planner",
        "Strategy Consultant",
        "Structural Engineer",
        "Stunt Performer / Stunt Coordinator",
        "Stylist",
        "Substance Abuse Counselor / Addiction Counselor",
        "Substitute Teacher",
        "Subtitler",
        "Subway Operator",
        "Supervisor",
        "Supply Chain Analyst",
        "Supply Chain Coordinator",
        "Supply Chain Director",
        "Supply Chain Manager",
        "Surgeon",
        "Surgical Oncologist",
        "Surgical Technician",
        "Surgical Technologist / Scrub Tech",
        "Surveyor (Land Surveyor)",
        "Sustainable Agriculture Specialist",
        "Swift Developer",
        "System Administrator",
        "Systems Analyst",
        "Systems Engineer",
        "Systems Integration Engineer",
        "Tailor / Seamstress",
        "Talent Acquisition Manager",
        "Talent Acquisition Specialist",
        "Talent Agent",
        "Talent Manager",
        "Tanning Salon Operator",
        "Tap Dancer",
        "Tarot Card Reader",
        "Tattoo Artist",
        "Tax Accountant",
        "Tax Advisor",
        "Tax Analyst",
        "Tax Consultant",
        "Tax Manager",
        "Tax Preparer",
        "Taxi Driver",
        "Taxidermist",
        "Tea Master / Taster",
        "Teacher",
        "Teacher's Assistant",
        "Teaching Assistant (University)",
        "Team Lead",
        "Team Lead (Retail)",
        "Team Manager (Logistics)",
        "Technical Account Manager",
        "Technical Illustrator",
        "Technical Lead",
        "Technical Program Manager",
        "Technical Recruiter",
        "Technical Support Engineer",
        "Technical Support Representative",
        "Technical Trainer",
        "Technical Writer",
        "Telecommunications Engineer",
        "Telemarketer",
        "Telemetry Nurse",
        "Television Director",
        "Television Producer",
        "Telex Operator",
        "Teller Supervisor",
        "Terminal Navigation",
        "Territory Manager",
        "Test Engineer",
        "Textile Designer",
        "Theater Director",
        "Theater Manager",
        "Theater Producer",
        "Theater Technician",
        "Theme Park Character Performer",
        "Theorist (Critical, Social, Political)",
        "Thoracic Surgeon",
        "Tile Setter",
        "Title Examiner",
        "Tool and Die Maker",
        "Tour Director",
        "Tour Guide",
        "Tour Operator",
        "Tow Truck Operator",
        "Town Clerk",
        "Town Planner",
        "Toxicologist",
        "Trader",
        "Traffic Engineer",
        "Traffic Manager",
        "Train Conductor",
        "Train Driver",
        "Training Coordinator",
        "Training Manager",
        "Training Specialist",
        "Translator",
        "Transit Manager",
        "Transplant Surgeon",
        "Transportation Analyst",
        "Transportation Coordinator",
        "Transportation Director",
        "Transportation Engineer",
        "Transportation Manager",
        "Transportation Planner",
        "Transportation Security Officer (TSA)",
        "Trauma Surgeon",
        "Travel Agent",
        "Travel Consultant",
        "Travel Nurse",
        "Treasury Analyst",
        "Tree Trimmer / Arborist",
        "Trial Lawyer",
        "Trivia Host",
        "Truck Dispatcher",
        "Truck Driver",
        "Trust Officer",
        "Tugboat Operator",
        "Tutor",
        "Type Designer",
        "Typographer",
        "UI Developer",
        "UI/UX Designer",
        "UI/UX Engineer",
        "UI/UX Researcher",
        "Ultrasound Technician",
        "Underwriter",
        "Unit Secretary / Ward Clerk",
        "Unity Developer",
        "University Administrator",
        "University Lecturer",
        "Unreal Engine Developer",
        "Upholsterer",
        "Urban Planner",
        "Urban Studies Specialist",
        "Urologist",
        "User Experience Writer (UX Writer)",
        "Utility Worker",
        "Utilization Review Nurse / Specialist",
        "Validation Engineer",
        "Valet Parker",
        "Vascular Surgeon",
        "Vascular Technologist",
        "Vendor Manager",
        "Venue Manager",
        "Veterinarian",
        "Veterinarian (DVM)",
        "Veterinary Assistant",
        "Veterinary Practice Manager",
        "Veterinary Technician",
        "Veterinary Technician (LVT/RVT/CVT)",
        "VFX Artist (Visual Effects)",
        "VFX Supervisor",
        "Vice President (VP)",
        "Video Editor",
        "Video Producer",
        "Videographer",
        "Vineyard Manager",
        "Vintner / Winemaker",
        "Virologist",
        "Visual Merchandiser",
        "Vocational Counselor",
        "Voice Actor",
        "Volcanologist",
        "Volunteer Coordinator",
        "Volunteer Management",
        "Vue.js Developer",
        "Waiter / Waitress",
        "Wardrobe Consultant",
        "Wardrobe Stylist (Entertainment)",
        "Warehouse Associate",
        "Warehouse Clerk",
        "Warehouse Manager",
        "Warehouse Supervisor",
        "Warehouse Worker",
        "Waste Management Worker",
        "Water Conservationist",
        "Water Quality Specialist",
        "Water Resources Engineer",
        "Water Treatment Plant Operator",
        "Web Analyst",
        "Web Content Manager",
        "Web Designer",
        "Web Developer",
        "Wedding Officiant",
        "Wedding Planner",
        "Welder",
        "Wellness Coordinator",
        "Wildlife Biologist",
        "Wildlife Rehabilitator",
        "Wind Turbine Technician",
        "Window Cleaner",
        "Wine Steward",
        "Winery Worker",
        "Windows System Administrator",
        "Wireless Engineer",
        "Woodworker",
        "Workforce Planning Analyst",
        "Wound Care Nurse",
        "Writer",
        "X-Ray Technician",
        "Yacht Crew / Captain",
        "Yardmaster",
        "Yoga Instructor",
        "Zookeeper",
        "Zoning Administrator",
        "Zoning Planner"
    )
}