package com.example.buildairesume

object BranchList {
    val Branches = mutableListOf(
        // **Computer & IT**
        "Computer Science Engineering",
        "Information Technology",
        "Artificial Intelligence & Machine Learning",
        "Data Science",
        "Cybersecurity",
        "Software Engineering",
        "Cloud Computing",
        "Internet of Things (IoT)",
        "Big Data Engineering",
        "Blockchain Engineering",
        "Computer Engineering",
        "Electronics and Computer Engineering",
        "Embedded Systems Engineering",

        // **Electronics & Electrical**
        "Electronics and Communication Engineering",
        "Electrical Engineering",
        "Electronics and Telecommunication Engineering",
        "Electronics and Instrumentation Engineering",
        "Microelectronics Engineering",
        "Power Engineering",
        "VLSI Design Engineering",

        // **Mechanical & Related Fields**
        "Mechanical Engineering",
        "Mechatronics Engineering",
        "Automobile Engineering",
        "Robotics Engineering",
        "Industrial Engineering",
        "Manufacturing Engineering",
        "Production Engineering",
        "Tool & Die Engineering",
        "Welding Engineering",
        "Thermal Engineering",

        // **Civil & Related Fields**
        "Civil Engineering",
        "Structural Engineering",
        "Construction Engineering",
        "Geotechnical Engineering",
        "Environmental Engineering",
        "Urban & Regional Planning",
        "Transportation Engineering",
        "Water Resources Engineering",
        "Infrastructure Engineering",

        // **Aerospace & Marine**
        "Aerospace Engineering",
        "Aeronautical Engineering",
        "Avionics Engineering",
        "Marine Engineering",
        "Naval Architecture",

        // **Chemical & Materials**
        "Chemical Engineering",
        "Biochemical Engineering",
        "Polymer Engineering",
        "Petroleum Engineering",
        "Mining Engineering",
        "Metallurgical Engineering",
        "Ceramic Engineering",
        "Textile Engineering",

        // **Biotech & Medical Tech**
        "Biotechnology Engineering",
        "Biomedical Engineering",
        "Genetic Engineering",
        "Nanotechnology Engineering",
        "Pharmaceutical Engineering",
        "Food Technology Engineering",
        "Agricultural Engineering",

        "MBA in Finance",
        "MBA in Marketing",
        "MBA in Human Resource Management (HRM)",
        "MBA in International Business",
        "MBA in Business Analytics",
        "MBA in Digital Marketing",
        "MBA in Operations Management",
        "MBA in Supply Chain Management",
        "MBA in Retail Management",
        "MBA in Healthcare Management",
        "MBA in Hospitality Management",
        "MBA in Tourism & Travel Management",
        "MBA in Information Technology (IT)",
        "MBA in Agri-Business",
        "MBA in Entrepreneurship",
        "MBA in Strategy & Consulting",
        "MBA in Event Management",
        "MBA in Sports Management",
        "MBA in Energy Management",
        "MBA in Media & Communication",
        "MBA in Public Policy",
        "MBA in Rural Management",
        "MBA in Family Business",
        "MBA in Luxury Brand Management",
        "MBA in E-Commerce",
        "MBA in Artificial Intelligence & Data Analytics",
        "MBA in Leadership & Organizational Strategy",

        "B.Sc in Computer Science",
        "B.Sc in Mathematics",
        "B.Sc in Physics",
        "B.Sc in Chemistry",
        "B.Sc in Biology",
        "B.Sc in Environmental Science",
        "B.Sc in Forensic Science",
        "B.Sc in Data Science",
        "B.Sc in Biotechnology",
        "B.Sc in Microbiology",
        "B.Sc in Statistics",
        "B.Sc in Agriculture",
        "B.Sc in Actuarial Science",
        "B.Sc in Nanoscience",
        "B.Sc in Biochemistry",

        // **Commerce & Finance**
        "B.Com (Bachelor of Commerce)",
        "B.Com in Accounting & Finance",
        "B.Com in Banking & Insurance",
        "B.Com in Business Analytics",
        "B.Com in E-Commerce",
        "BBA (Bachelor of Business Administration)",
        "BBA in Finance",
        "BBA in Marketing",
        "BBA in HRM",
        "BBA in International Business",
        "BBA in Retail Management",
        "BBA in Digital Marketing",
        "BBA in Entrepreneurship",

        // **Law Degrees**
        "LLB (Bachelor of Laws)",
        "BA LLB",
        "BBA LLB",
        "B.Com LLB",
        "LLM (Master of Laws)",
        "Diploma in Cyber Law",
        "Diploma in Intellectual Property Law",

        // **Medical & Healthcare**
        "MBBS (Bachelor of Medicine & Bachelor of Surgery)",
        "BDS (Dentistry)",
        "BAMS (Ayurvedic Medicine)",
        "BHMS (Homeopathy Medicine)",
        "BUMS (Unani Medicine)",
        "BPT (Physiotherapy)",
        "B.Pharm (Pharmacy)",
        "B.Sc in Nursing",
        "B.Sc in Nutrition & Dietetics",
        "B.Sc in Radiology",
        "B.Sc in Medical Laboratory Technology",
        "B.Sc in Occupational Therapy",
        "B.Sc in Optometry",
        "M.Sc in Biotechnology",
        "M.Sc in Microbiology",
        "M.Sc in Genetics",
        "M.Sc in Neuroscience",

        // **Arts, Humanities & Social Sciences**
        "BA in English Literature",
        "BA in Political Science",
        "BA in History",
        "BA in Sociology",
        "BA in Psychology",
        "BA in Economics",
        "BA in Public Administration",
        "BA in Journalism & Mass Communication",
        "BA in Anthropology",
        "BA in Philosophy",
        "BA in International Relations",
        "BA in Fine Arts",
        "BA in Performing Arts",

        // **Education & Teaching**
        "B.Ed (Bachelor of Education)",
        "M.Ed (Master of Education)",
        "Diploma in Early Childhood Education",
        "Diploma in Special Education",
        "M.A in Education",
        "PhD in Education",

        // **Hotel & Hospitality Management**
        "BHM (Bachelor of Hotel Management)",
        "B.Sc in Hospitality Management",
        "B.Sc in Travel & Tourism Management",
        "Diploma in Hotel Management",
        "Diploma in Culinary Arts",
        "M.Sc in Hospitality & Tourism Management",

        // **Architecture & Planning**
        "B.Arch (Bachelor of Architecture)",
        "M.Arch (Master of Architecture)",
        "B.Plan (Bachelor of Planning)",
        "M.Plan (Master of Planning)",
        "Diploma in Interior Design",
        "Diploma in Landscape Architecture",

        // **Other Specialized Degrees**
        "B.Des (Bachelor of Design)",
        "M.Des (Master of Design)",
        "BFA (Bachelor of Fine Arts)",
        "MFA (Master of Fine Arts)",
        "B.Sc in Animation & VFX",
        "Diploma in Graphic Design",
        "B.Sc in Game Design & Development",
        "B.Sc in Film & Television Production",
        "B.Sc in Ethical Hacking",
        "B.Sc in Cybersecurity",
        "B.Sc in Artificial Intelligence & Robotics",
        "B.Sc in Machine Learning",
        "B.Sc in Virtual Reality & Augmented Reality"
    )
}
