package com.example.buildairesume

object JobList {

    val jobList = mutableListOf(
        // --- Software, IT & Data ---
        "AI Engineer",
        "AI Researcher",
        "Android Developer",
        "Android Designer",
        "Android Engineer",
        "Android UI/UX Designer",
        "Angular Developer",
        "Application Developer",
        "Application Security Engineer",
        "Automation Engineer",
        "Automation Tester",
        "AWS Solutions Architect",
        "Azure Cloud Engineer",
        "Backend Developer",
        "Big Data Engineer",
        "Blockchain Developer",
        "Business Intelligence Analyst",
        "Business Intelligence Developer",
        "C++ Developer",
        "Cloud Architect",
        "Cloud Consultant",
        "Cloud Engineer",
        "Cloud Security Engineer",
        "Computer Vision Engineer",
        "CRM Developer",
        "Cyber Security Analyst",
        "Cyber Security Consultant",
        "Cyber Security Engineer",
        "Data Analyst",
        "Data Architect",
        "Data Engineer",
        "Data Scientist",
        "Data Warehouse Engineer",
        "Database Administrator (DBA)",
        "Database Developer",
        "Deep Learning Engineer",
        "Desktop Support Technician",
        "DevOps Engineer",
        "Embedded Systems Engineer",
        "Ethical Hacker",
        "Firmware Engineer",
        "Flutter Developer",
        "Frontend Developer",
        "Full Stack Developer",
        "GCP Cloud Engineer",
        "Game Designer",
        "Game Developer",
        "Game Programmer",
        "Gameplay Programmer",
        "Go Developer (Golang)",
        "Hardware Engineer",
        "Help Desk Analyst",
        "Help Desk Technician",
        "Incident Responder",
        "Information Security Analyst",
        "Information Security Manager",
        "Infrastructure Engineer",
        "iOS Developer",
        "iOS Engineer",
        "iOS UI/UX Designer",
        "IoT Developer",
        "IT Auditor",
        "IT Consultant",
        "IT Coordinator",
        "IT Director",
        "IT Manager",
        "IT Project Manager",
        "IT Specialist",
        "IT Support Specialist",
        "Java Developer",
        "JavaScript Developer",
        "Kotlin Developer",
        "Linux System Administrator",
        "Machine Learning Engineer",
        "Manual Tester",
        "Mobile App Developer",
        "Mobile Engineer",
        ".NET Developer",
        "Network Administrator",
        "Network Architect",
        "Network Engineer",
        "Network Security Engineer",
        "Network Technician",
        "NLP Engineer (Natural Language Processing)",
        "NoSQL Database Administrator",
        "Oracle Developer",
        "Penetration Tester",
        "PHP Developer",
        "Platform Engineer",
        "Product Owner",
        "Python Developer",
        "QA Analyst (Quality Assurance)",
        "QA Engineer (Quality Assurance)",
        "QA Lead (Quality Assurance)",
        "QA Manager (Quality Assurance)",
        "React Developer",
        "React Native Developer",
        "Release Engineer",
        "Robotics Engineer",
        "Ruby on Rails Developer",
        "Rust Developer",
        "Salesforce Administrator",
        "Salesforce Developer",
        "Scala Developer",
        "Scrum Master",
        "Security Architect",
        "Security Consultant",
        "Security Operations Center (SOC) Analyst",
        "SEO Specialist (Search Engine Optimization)",
        "SharePoint Developer",
        "Site Reliability Engineer (SRE)",
        "Smart Contract Developer",
        "Software Architect",
        "Software Developer",
        "Software Engineer",
        "Software Engineering Manager",
        "Software Tester",
        "Solidity Developer",
        "Solutions Architect",
        "SQL Developer",
        "Swift Developer",
        "System Administrator",
        "Systems Analyst",
        "Systems Engineer",
        "Technical Account Manager",
        "Technical Lead",
        "Technical Program Manager",
        "Technical Recruiter",
        "Technical Support Engineer",
        "Technical Writer",
        "Telecommunications Engineer",
        "UI Developer",
        "UI/UX Designer",
        "UI/UX Engineer",
        "UI/UX Researcher",
        "Unity Developer",
        "Unreal Engine Developer",
        "Vue.js Developer",
        "Web Analyst",
        "Web Designer",
        "Web Developer",
        "Windows System Administrator",
        "Wireless Engineer",

        // --- Engineering (Non-Software) & Architecture ---
        "Aerospace Engineer",
        "Agricultural Engineer",
        "Architect",
        "Architectural Drafter",
        "Architectural Technologist",
        "Automotive Engineer",
        "Biomedical Engineer",
        "CAD Designer",
        "CAD Technician",
        "Chemical Engineer",
        "Civil Engineer",
        "Construction Engineer",
        "Construction Manager",
        "Construction Superintendent",
        "Design Engineer",
        "Drafter",
        "Electrical Design Engineer",
        "Electrical Engineer",
        "Electronics Engineer",
        "Energy Engineer",
        "Environmental Engineer",
        "Facilities Engineer",
        "Geotechnical Engineer",
        "Hardware Design Engineer",
        "Industrial Designer",
        "Industrial Engineer",
        "Interior Architect",
        "Interior Designer",
        "Landscape Architect",
        "Manufacturing Engineer",
        "Marine Engineer",
        "Materials Engineer",
        "Mechanical Design Engineer",
        "Mechanical Engineer",
        "Mechatronics Engineer",
        "Mining Engineer",
        "Naval Architect",
        "Nuclear Engineer",
        "Petroleum Engineer",
        "Process Engineer",
        "Product Design Engineer",
        "Project Architect",
        "Project Engineer",
        "Quality Engineer",
        "Safety Engineer",
        "Solar Energy Engineer",
        "Structural Engineer",
        "Surveyor (Land Surveyor)",
        "Systems Integration Engineer",
        "Test Engineer",
        "Transportation Engineer",
        "Urban Planner",
        "Validation Engineer",
        "Water Resources Engineer",

        // --- Business, Management, Finance & Operations ---
        "Account Executive",
        "Account Manager",
        "Accountant",
        "Accounts Payable Clerk",
        "Accounts Receivable Clerk",
        "Actuary",
        "Administrative Assistant",
        "Admissions Counselor",
        "Advertising Manager",
        "Auditor (Internal/External)",
        "Benefits Specialist",
        "Bookkeeper",
        "Brand Manager",
        "Budget Analyst",
        "Business Analyst",
        "Business Consultant",
        "Business Development Manager",
        "Business Development Representative",
        "Business Owner",
        "Buyer",
        "Category Manager",
        "Chief Administrative Officer (CAO)",
        "Chief Compliance Officer (CCO)",
        "Chief Data Officer (CDO)",
        "Chief Diversity Officer (CDO)",
        "Chief Executive Officer (CEO)",
        "Chief Financial Officer (CFO)",
        "Chief Human Resources Officer (CHRO)",
        "Chief Information Officer (CIO)",
        "Chief Information Security Officer (CISO)",
        "Chief Marketing Officer (CMO)",
        "Chief Operating Officer (COO)",
        "Chief People Officer (CPO)",
        "Chief Product Officer (CPO)",
        "Chief Revenue Officer (CRO)",
        "Chief Strategy Officer (CSO)",
        "Chief Sustainability Officer (CSO)",
        "Chief Technology Officer (CTO)",
        "Claims Adjuster",
        "Client Relationship Manager",
        "Commercial Manager",
        "Communications Manager",
        "Communications Specialist",
        "Compensation Analyst",
        "Compensation & Benefits Manager",
        "Compliance Manager",
        "Compliance Officer",
        "Construction Project Manager",
        "Consultant",
        "Content Manager",
        "Content Strategist",
        "Contract Manager",
        "Controller",
        "Corporate Counsel",
        "Cost Accountant",
        "Credit Analyst",
        "Customer Success Manager",
        "Digital Marketing Manager",
        "Digital Marketing Specialist",
        "Director",
        "Diversity & Inclusion Manager",
        "Economist",
        "Email Marketing Specialist",
        "Employee Relations Specialist",
        "Entrepreneur",
        "Environmental Consultant",
        "Estimator",
        "Event Coordinator",
        "Event Manager",
        "Event Planner",
        "Executive Assistant",
        "Facilities Manager",
        "Finance Director",
        "Finance Manager",
        "Financial Advisor",
        "Financial Analyst",
        "Financial Consultant",
        "Financial Controller",
        "Financial Planner",
        "Forensic Accountant",
        "Founder",
        "Franchise Owner",
        "Fund Manager",
        "Fundraiser",
        "General Manager",
        "Government Relations Manager",
        "Grant Writer",
        "HR Administrator",
        "HR Analyst",
        "HR Assistant",
        "HR Business Partner",
        "HR Coordinator",
        "HR Director",
        "HR Generalist",
        "HR Manager",
        "HR Specialist",
        "Human Resources Information Systems (HRIS) Analyst",
        "Import/Export Specialist",
        "Inside Sales Representative",
        "Insurance Agent",
        "Insurance Underwriter",
        "Internal Auditor",
        "International Business Manager",
        "Inventory Manager",
        "Investment Analyst",
        "Investment Banker",
        "Investor Relations Manager",
        "Key Account Manager",
        "Knowledge Manager",
        "Labor Relations Specialist",
        "Learning & Development Coordinator",
        "Learning & Development Manager",
        "Leasing Consultant",
        "Legal Secretary",
        "Lobbyist",
        "Logistics Analyst",
        "Logistics Coordinator",
        "Logistics Manager",
        "Management Analyst",
        "Management Consultant",
        "Market Research Analyst",
        "Marketing Analyst",
        "Marketing Assistant",
        "Marketing Coordinator",
        "Marketing Director",
        "Marketing Manager",
        "Marketing Operations Manager",
        "Marketing Specialist",
        "Media Buyer",
        "Merchandiser",
        "Mortgage Broker",
        "Non-Profit Director",
        "Office Administrator",
        "Office Assistant",
        "Office Manager",
        "Operations Analyst",
        "Operations Coordinator",
        "Operations Director",
        "Operations Manager",
        "Operations Supervisor",
        "Organizational Development Consultant",
        "Outside Sales Representative",
        "Paralegal",
        "Partner",
        "Payroll Manager",
        "Payroll Specialist",
        "Performance Management Specialist",
        "Personal Assistant",
        "PPC Specialist (Pay-Per-Click)",
        "Principal",
        "Procurement Manager",
        "Procurement Specialist",
        "Product Manager",
        "Product Marketing Manager",
        "Production Manager",
        "Program Coordinator",
        "Program Director",
        "Program Manager",
        "Project Administrator",
        "Project Analyst",
        "Project Coordinator",
        "Project Manager",
        "Property Manager",
        "Public Relations Manager",
        "Public Relations Specialist",
        "Purchasing Agent",
        "Purchasing Manager",
        "Real Estate Agent",
        "Real Estate Appraiser",
        "Real Estate Broker",
        "Receptionist",
        "Recruiter",
        "Recruitment Coordinator",
        "Recruitment Manager",
        "Recruitment Specialist",
        "Regional Manager",
        "Relationship Manager",
        "Research Analyst",
        "Retail Buyer",
        "Retail Manager",
        "Risk Analyst",
        "Risk Manager",
        "Sales Analyst",
        "Sales Associate",
        "Sales Consultant",
        "Sales Coordinator",
        "Sales Director",
        "Sales Engineer",
        "Sales Manager",
        "Sales Operations Manager",
        "Sales Representative",
        "Scheduler",
        "SEM Specialist (Search Engine Marketing)",
        "SEO Manager",
        "Shift Supervisor",
        "Social Media Coordinator",
        "Social Media Manager",
        "Social Media Specialist",
        "Sourcing Specialist",
        "Staff Accountant",
        "Statistician",
        "Stockbroker",
        "Store Manager",
        "Strategic Planner",
        "Strategy Consultant",
        "Supply Chain Analyst",
        "Supply Chain Coordinator",
        "Supply Chain Manager",
        "Talent Acquisition Manager",
        "Talent Acquisition Specialist",
        "Tax Accountant",
        "Tax Advisor",
        "Tax Analyst",
        "Tax Consultant",
        "Tax Manager",
        "Tax Preparer",
        "Team Lead",
        "Territory Manager",
        "Trader",
        "Training Coordinator",
        "Training Manager",
        "Training Specialist",
        "Transportation Manager",
        "Treasury Analyst",
        "Underwriter",
        "Vendor Manager",
        "Vice President (VP)",
        "Visual Merchandiser",
        "Warehouse Manager",
        "Warehouse Supervisor",
        "Workforce Planning Analyst",

        // --- Healthcare & Medicine ---
        "Acupuncturist",
        "Anesthesiologist",
        "Art Therapist",
        "Athletic Trainer",
        "Audiologist",
        "Behavioral Therapist",
        "Biomedical Scientist",
        "Cardiologist",
        "Caregiver",
        "Case Manager",
        "Certified Nursing Assistant (CNA)",
        "Chiropractor",
        "Clinical Director",
        "Clinical Lab Scientist",
        "Clinical Psychologist",
        "Clinical Research Associate (CRA)",
        "Clinical Research Coordinator",
        "Clinical Social Worker",
        "Counselor",
        "Dental Assistant",
        "Dental Hygienist",
        "Dentist",
        "Dermatologist",
        "Dietitian",
        "Doctor",
        "Emergency Medical Technician (EMT)",
        "Endocrinologist",
        "Family Physician",
        "Forensic Psychologist",
        "Gastroenterologist",
        "General Practitioner (GP)",
        "Genetic Counselor",
        "Geriatric Care Manager",
        "Health Coach",
        "Healthcare Administrator",
        "Healthcare Consultant",
        "Hematologist",
        "Home Health Aide",
        "Hospital Administrator",
        "Immunologist",
        "Lab Manager",
        "Lab Technician",
        "Licensed Practical Nurse (LPN)",
        "Massage Therapist",
        "Medical Assistant",
        "Medical Biller",
        "Medical Coder",
        "Medical Director",
        "Medical Illustrator",
        "Medical Laboratory Technician",
        "Medical Librarian",
        "Medical Officer",
        "Medical Physicist",
        "Medical Receptionist",
        "Medical Researcher",
        "Medical Sales Representative",
        "Medical Secretary",
        "Medical Social Worker",
        "Medical Technician",
        "Medical Transcriptionist",
        "Medical Writer",
        "Mental Health Counselor",
        "Midwife",
        "Music Therapist",
        "Neonatologist",
        "Nephrologist",
        "Neurologist",
        "Nurse Anesthetist",
        "Nurse Manager",
        "Nurse Practitioner (NP)",
        "Nurse (Registered Nurse - RN)",
        "Nutritionist",
        "Obstetrician/Gynecologist (OB/GYN)",
        "Occupational Therapist",
        "Occupational Therapy Assistant",
        "Oncologist",
        "Ophthalmologist",
        "Optician",
        "Optometrist",
        "Oral Surgeon",
        "Orthodontist",
        "Orthopedic Surgeon",
        "Otolaryngologist (ENT)",
        "Paramedic",
        "Pathologist",
        "Pediatrician",
        "Pharmaceutical Sales Representative",
        "Pharmacist",
        "Pharmacy Technician",
        "Phlebotomist",
        "Physical Therapist",
        "Physical Therapy Assistant",
        "Physician",
        "Physician Assistant (PA)",
        "Podiatrist",
        "Practice Manager",
        "Psychiatrist",
        "Psychologist",
        "Public Health Official",
        "Pulmonologist",
        "Radiation Therapist",
        "Radiographer",
        "Radiologic Technologist",
        "Radiologist",
        "Recreational Therapist",
        "Registered Dietitian (RD)",
        "Research Assistant (Medical)",
        "Respiratory Therapist",
        "Rheumatologist",
        "School Nurse",
        "School Psychologist",
        "Sonographer",
        "Speech Language Pathologist",
        "Speech Therapist",
        "Sports Therapist",
        "Surgeon",
        "Surgical Technician",
        "Ultrasound Technician",
        "Urologist",
        "Veterinarian",
        "Veterinary Assistant",
        "Veterinary Technician",
        "Wellness Coordinator",
        "X-Ray Technician",

        // --- Education, Research & Academia ---
        "Academic Advisor",
        "Admissions Director",
        "Archivist",
        "Art Teacher",
        "Assistant Professor",
        "Associate Professor",
        "Career Counselor",
        "Childcare Worker",
        "College Counselor",
        "College Professor",
        "Corporate Trainer",
        "Curator",
        "Curriculum Developer",
        "Dean",
        "Distance Learning Coordinator",
        "Education Administrator",
        "Education Consultant",
        "Elementary School Teacher",
        "ESL Teacher (English as a Second Language)",
        "Guidance Counselor",
        "Head Teacher / Principal",
        "High School Teacher",
        "Historian",
        "Instructional Coordinator",
        "Instructional Designer",
        "Instructional Technologist",
        "Lab Assistant (Research)",
        "Language Instructor",
        "Lecturer",
        "Librarian",
        "Library Assistant",
        "Literacy Specialist",
        "Middle School Teacher",
        "Museum Educator",
        "Music Teacher",
        "Nanny",
        "Online Instructor",
        "Physical Education Teacher",
        "Postdoctoral Researcher",
        "Preschool Teacher",
        "Professor",
        "Provost",
        "Registrar",
        "Research Analyst",
        "Research Assistant",
        "Research Associate",
        "Research Director",
        "Research Scientist",
        "Researcher",
        "School Administrator",
        "School Counselor",
        "School Librarian",
        "School Principal",
        "Science Teacher",
        "Sociologist",
        "Special Education Teacher",
        "Substitute Teacher",
        "Teacher",
        "Teacher's Assistant",
        "Teaching Assistant (University)",
        "Technical Trainer",
        "Tutor",
        "University Administrator",
        "University Lecturer",
        "Vocational Counselor",

        // --- Legal, Law Enforcement & Security ---
        "Arbitrator",
        "Attorney",
        "Bailiff",
        "Border Patrol Agent",
        "Compliance Attorney",
        "Contract Attorney",
        "Corporate Lawyer",
        "Correctional Officer",
        "Court Clerk",
        "Court Interpreter",
        "Court Reporter",
        "Crime Analyst",
        "Criminal Investigator",
        "Cybercrime Investigator",
        "Detective",
        "Dispatcher (Emergency)",
        "FBI Agent",
        "Firefighter",
        "Fire Inspector",
        "Forensic Accountant",
        "Forensic Anthropologist",
        "Forensic Artist",
        "Forensic Chemist",
        "Forensic Scientist",
        "Forensic Technician",
        "Immigration Officer",
        "Intelligence Analyst",
        "Intellectual Property Lawyer",
        "Investigator",
        "Judge",
        "Law Clerk",
        "Law Professor",
        "Lawyer",
        "Legal Advisor",
        "Legal Analyst",
        "Legal Assistant",
        "Legal Consultant",
        "Litigation Support Specialist",
        "Mediator",
        "Paralegal",
        "Parole Officer",
        "Patent Attorney",
        "Police Officer",
        "Private Investigator",
        "Probation Officer",
        "Prosecutor",
        "Public Defender",
        "Security Consultant",
        "Security Director",
        "Security Guard",
        "Security Manager",
        "Security Officer",
        "Sheriff",
        "State Trooper",
        "Title Examiner",
        "Trial Lawyer",
        "Trust Officer",

        // --- Media, Design, Arts & Communication ---
        "3D Animator",
        "3D Artist",
        "3D Modeler",
        "Actor",
        "Animator",
        "Announcer",
        "Art Critic",
        "Art Director",
        "Art Handler",
        "Art Teacher", // Also in Education
        "Audio Engineer",
        "Author",
        "Blogger",
        "Broadcast Journalist",
        "Broadcast Technician",
        "Camera Operator",
        "Choreographer",
        "Cinematographer",
        "Colorist",
        "Comedian",
        "Communications Director", // Also in Business
        "Composer",
        "Concept Artist",
        "Conservator",
        "Content Creator",
        "Content Editor",
        "Content Writer",
        "Copy Editor",
        "Copywriter",
        "Costume Designer",
        "Creative Director",
        "Creative Strategist",
        "Dancer",
        "Desktop Publisher",
        "Digital Artist",
        "Disc Jockey (DJ)",
        "Documentary Filmmaker",
        "Editor",
        "Editorial Assistant",
        "Fashion Designer",
        "Fashion Stylist",
        "Film Critic",
        "Film Director",
        "Film Editor",
        "Film Producer",
        "Floral Designer",
        "Furniture Designer",
        "Game Artist",
        "Ghostwriter",
        "Goldsmith",
        "Grant Writer", // Also in Business
        "Graphic Artist",
        "Graphic Designer",
        "Illustrator",
        "Industrial Designer", // Also in Engineering
        "Interpreter",
        "Jeweler",
        "Journalist",
        "Landscape Designer",
        "Layout Artist",
        "Level Designer", // Also in IT/Game Dev
        "Lighting Designer",
        "Linguist",
        "Makeup Artist",
        "Media Planner", // Also in Business
        "Medical Illustrator", // Also in Healthcare
        "Motion Graphics Designer",
        "Multimedia Artist",
        "Museum Technician",
        "Music Producer",
        "Music Therapist", // Also in Healthcare
        "Musical Director",
        "Musician",
        "Narrative Designer", // Also in IT/Game Dev
        "News Anchor",
        "News Producer",
        "News Reporter",
        "Painter (Artist)",
        "Pattern Maker",
        "Photo Editor",
        "Photographer",
        "Photojournalist",
        "Playwright",
        "Podcast Host",
        "Podcaster",
        "Poet",
        "Potter / Ceramist",
        "Printmaker",
        "Producer (Film/TV/Radio)",
        "Production Artist",
        "Production Assistant",
        "Production Coordinator",
        "Production Designer",
        "Proofreader",
        "Publisher",
        "Radio Host",
        "Radio Producer",
        "Reporter",
        "Screenwriter",
        "Sculptor",
        "Set Decorator",
        "Set Designer",
        "Singer",
        "Sound Designer",
        "Sound Editor",
        "Sound Engineer",
        "Sound Mixer",
        "Stage Manager",
        "Story Artist",
        "Storyboard Artist",
        "Stylist",
        "Subtitler",
        "Tattoo Artist",
        "Technical Illustrator",
        "Technical Writer", // Also in IT
        "Television Director",
        "Television Producer",
        "Textile Designer",
        "Translator",
        "Type Designer",
        "Typographer",
        "User Experience Writer (UX Writer)",
        "VFX Artist (Visual Effects)",
        "VFX Supervisor",
        "Video Editor",
        "Video Producer",
        "Videographer",
        "Voice Actor",
        "Web Content Manager",
        "Writer",

        // --- Hospitality, Tourism, Food & Beverage ---
        "Baker",
        "Banquet Manager",
        "Bar Manager",
        "Barista",
        "Bartender",
        "Bed & Breakfast Owner",
        "Bellhop",
        "Booking Agent",
        "Busser",
        "Butcher",
        "Cafe Manager",
        "Caterer",
        "Catering Manager",
        "Chef",
        "Chef de Partie",
        "Concierge",
        "Cook",
        "Cruise Director",
        "Dishwasher",
        "Executive Chef",
        "Executive Housekeeper",
        "Fast Food Worker",
        "Flight Attendant",
        "Food & Beverage Director",
        "Food & Beverage Manager",
        "Food Critic",
        "Food Scientist",
        "Food Service Manager",
        "Food Stylist",
        "Front Desk Agent",
        "Front Desk Clerk",
        "Front Desk Manager",
        "General Manager (Hotel/Restaurant)",
        "Guest Relations Manager",
        "Guest Service Agent",
        "Host / Hostess",
        "Hotel Clerk",
        "Hotel Concierge",
        "Hotel Manager",
        "Housekeeper",
        "Housekeeping Manager",
        "Kitchen Manager",
        "Kitchen Porter",
        "Line Cook",
        "Maitre d'",
        "Mixologist",
        "Pastry Chef",
        "Porter",
        "Prep Cook",
        "Reservation Agent",
        "Restaurant General Manager",
        "Restaurant Manager",
        "Room Attendant",
        "Server",
        "Short Order Cook",
        "Sommelier",
        "Sous Chef",
        "Spa Manager",
        "Tour Guide",
        "Tour Operator",
        "Travel Agent",
        "Travel Consultant",
        "Valet Parker",
        "Waiter / Waitress",
        "Wedding Planner",
        "Wine Steward",

        // --- Skilled Trades & Manual Labor ---
        "Aircraft Mechanic",
        "Appliance Repair Technician",
        "Assembler",
        "Auto Body Technician",
        "Automotive Glass Technician",
        "Automotive Mechanic",
        "Automotive Technician",
        "Blacksmith",
        "Boilermaker",
        "Bricklayer",
        "Building Inspector",
        "Cabinet Maker",
        "Carpenter",
        "Carpet Installer",
        "Cement Mason",
        "Concrete Finisher",
        "Construction Foreman",
        "Construction Laborer",
        "Construction Worker",
        "Crane Operator",
        "Customs Broker",
        "Diesel Mechanic",
        "Diver",
        "Drywall Finisher",
        "Drywall Installer",
        "Electrician",
        "Elevator Mechanic",
        "Equipment Operator",
        "Fabricator",
        "Farm Worker",
        "Fence Erector",
        "Fisherman",
        "Floor Layer",
        "Forklift Operator",
        "Framer",
        "Furniture Finisher",
        "Gardener",
        "General Contractor",
        "Glazier",
        "Groundskeeper",
        "Handyman",
        "Heavy Equipment Operator",
        "HVAC Installer",
        "HVAC Technician",
        "Insulation Worker",
        "Ironworker",
        "Janitor",
        "Landscaper",
        "Lineman",
        "Locksmith",
        "Logger",
        "Machine Operator",
        "Machinist",
        "Maintenance Manager",
        "Maintenance Supervisor",
        "Maintenance Technician",
        "Maintenance Worker",
        "Marine Mechanic",
        "Mason",
        "Material Handler",
        "Mechanic",
        "Metal Fabricator",
        "Millwright",
        "Mover",
        "Operating Engineer",
        "Painter",
        "Pest Control Technician",
        "Pipefitter",
        "Plasterer",
        "Plumber",
        "Power Plant Operator",
        "Production Worker",
        "Rigger",
        "Roofer",
        "Scaffolder",
        "Sheet Metal Worker",
        "Shipfitter",
        "Small Engine Mechanic",
        "Solar Panel Installer",
        "Sprinkler Fitter",
        "Steamfitter",
        "Stonemason",
        "Tailor / Seamstress",
        "Tile Setter",
        "Tool and Die Maker",
        "Tree Trimmer / Arborist",
        "Truck Driver",
        "Upholsterer",
        "Utility Worker",
        "Waste Management Worker",
        "Water Treatment Plant Operator",
        "Welder",
        "Window Cleaner",
        "Wind Turbine Technician",
        "Woodworker",

        // --- Science & Research (Non-Medical/Edu) ---
        "Agronomist",
        "Analytical Chemist",
        "Animal Scientist",
        "Anthropologist",
        "Archaeologist",
        "Astronomer",
        "Astrophysicist",
        "Atmospheric Scientist",
        "Biochemist",
        "Bioinformatician",
        "Biologist",
        "Biophysicist",
        "Biostatistician",
        "Botanist",
        "Cartographer",
        "Cell Biologist",
        "Chemist",
        "Climatologist",
        "Conservation Scientist",
        "Ecologist",
        "Entomologist",
        "Environmental Chemist",
        "Environmental Consultant",
        "Environmental Planner",
        "Environmental Scientist",
        "Environmental Specialist",
        "Environmental Technician",
        "Epidemiologist",
        "Food Scientist", // Also in Hospitality
        "Forester",
        "Geneticist",
        "Geochemist",
        "Geographer",
        "Geologist",
        "Geophysicist",
        "GIS Analyst (Geographic Information Systems)",
        "GIS Specialist",
        "Horticulturist",
        "Hydrologist",
        "Ichthyologist",
        "Immunologist", // Also in Healthcare
        "Lab Manager", // Also in Healthcare
        "Limnologist",
        "Marine Biologist",
        "Materials Scientist",
        "Mathematician",
        "Meteorologist",
        "Microbiologist",
        "Molecular Biologist",
        "Mycologist",
        "Nanotechnologist",
        "Oceanographer",
        "Ornithologist",
        "Paleontologist",
        "Park Naturalist",
        "Park Ranger",
        "Pharmacologist",
        "Physicist",
        "Plant Scientist",
        "Polymer Scientist",
        "Primatologist",
        "Quantitative Analyst ('Quant')",
        "Remote Sensing Scientist",
        "Seismologist",
        "Soil Scientist",
        "Space Scientist",
        "Toxicologist",
        "Virologist",
        "Volcanologist",
        "Wildlife Biologist",
        "Zoologist",

        // --- Transportation & Logistics ---
        "Air Traffic Controller",
        "Aircraft Dispatcher",
        "Airline Pilot",
        "Airport Manager",
        "Aviation Manager",
        "Barge Operator",
        "Bus Driver",
        "Cargo Handler",
        "Chauffeur",
        "Commercial Pilot",
        "Courier",
        "Delivery Driver",
        "Dispatcher",
        "Dock Worker",
        "Drone Pilot",
        "Fleet Manager",
        "Flight Dispatcher",
        "Freight Agent",
        "Freight Broker",
        "Freight Forwarder",
        "Helicopter Pilot",
        "Locomotive Engineer",
        "Logistics Analyst", // Also in Business
        "Logistics Coordinator", // Also in Business
        "Logistics Manager", // Also in Business
        "Logistics Specialist",
        "Longshoreman",
        "Mail Carrier",
        "Marine Oiler",
        "Merchant Mariner",
        "Pilot",
        "Port Manager",
        "Railroad Conductor",
        "Railroad Engineer",
        "Route Driver",
        "Sailor",
        "Ship Captain",
        "Ship Engineer", // Also in Engineering
        "Ship Pilot",
        "Shipping and Receiving Clerk",
        "Station Agent (Train/Bus)",
        "Subway Operator",
        "Supply Chain Director", // Also in Business
        "Taxi Driver",
        "Tow Truck Operator",
        "Traffic Engineer",
        "Traffic Manager",
        "Train Conductor",
        "Transit Manager",
        "Transportation Analyst",
        "Transportation Coordinator",
        "Transportation Director",
        "Transportation Manager",
        "Transportation Planner",
        "Transportation Security Officer (TSA)",
        "Truck Dispatcher",
        "Truck Driver",
        "Warehouse Associate",
        "Warehouse Clerk",
        "Warehouse Manager", // Also in Business
        "Warehouse Worker",
        "Yardmaster",

        // --- Personal Care, Fitness & Wellness ---
        "Aesthetician / Esthetician",
        "Barber",
        "Beautician",
        "Childcare Center Director", // Also in Education
        "Cosmetologist",
        "Dog Groomer",
        "Dog Trainer",
        "Electrologist",
        "Embalmer",
        "Fitness Center Manager",
        "Fitness Instructor",
        "Funeral Director",
        "Group Fitness Instructor",
        "Gym Manager",
        "Hair Stylist",
        "Holistic Health Practitioner",
        "Life Coach",
        "Manicurist / Pedicurist",
        "Massage Therapist", // Also in Healthcare
        "Mortician",
        "Nail Technician",
        "Personal Fitness Trainer",
        "Personal Shopper",
        "Pet Groomer",
        "Pet Sitter",
        "Pilates Instructor",
        "Reiki Practitioner",
        "Skincare Specialist",
        "Spa Attendant",
        "Spa Therapist",
        "Tanning Salon Operator",
        "Wardrobe Consultant",
        "Yoga Instructor",

        // --- Retail & Customer Service ---
        "Assistant Buyer",
        "Assistant Manager (Retail)",
        "Baker", // Also in Hospitality
        "Bank Teller",
        "Brand Ambassador",
        "Butcher", // Also in Hospitality
        "Call Center Agent",
        "Call Center Manager",
        "Call Center Representative",
        "Cashier",
        "Client Advisor",
        "Customer Care Representative",
        "Customer Service Assistant",
        "Customer Service Manager",
        "Customer Service Representative",
        "Customer Service Supervisor",
        "Department Manager (Retail)",
        "District Manager (Retail)",
        "E-commerce Manager",
        "E-commerce Specialist",
        "Floral Designer", // Also in Media/Design
        "Floor Manager",
        "Greeter",
        "Grocery Clerk",
        "Head Cashier",
        "Jeweler", // Also in Media/Design
        "Key Holder",
        "Loss Prevention Agent",
        "Loss Prevention Manager",
        "Luxury Goods Advisor",
        "Merchandise Planner",
        "Merchandiser", // Also in Business
        "Optician", // Also in Healthcare
        "Personal Banker",
        "Pharmacist", // Also in Healthcare
        "Pharmacy Technician", // Also in Healthcare
        "Produce Manager",
        "Product Demonstrator",
        "Relationship Banker",
        "Retail Associate",
        "Retail Banker",
        "Retail Manager", // Also in Business
        "Retail Merchandiser",
        "Retail Sales Associate",
        "Retail Sales Consultant",
        "Retail Supervisor",
        "Sales Assistant",
        "Sales Associate", // Also in Business
        "Sales Clerk",
        "Sales Floor Associate",
        "Shift Lead",
        "Shift Manager",
        "Shopper",
        "Stock Clerk",
        "Stocker",
        "Store Clerk",
        "Store Detective",
        "Store Manager", // Also in Business
        "Supervisor",
        "Team Lead (Retail)",
        "Technical Support Representative", // Can be retail/customer service facing
        "Telemarketer",
        "Teller Supervisor",
        "Visual Merchandiser", // Also in Business

        // --- Government, Public Service & Non-Profit ---
        "Administrative Officer (Government)",
        "Agricultural Inspector",
        "Archivist", // Also in Education
        "Assessor",
        "Case Worker",
        "Child Protective Services Worker",
        "City Clerk",
        "City Manager",
        "Civil Servant",
        "Community Development Manager",
        "Community Health Worker",
        "Community Organizer",
        "Congressional Aide",
        "Conservation Officer",
        "Consular Officer",
        "County Clerk",
        "Customs Officer",
        "Development Director (Non-Profit)",
        "Diplomat",
        "Economic Development Officer",
        "Election Official",
        "Emergency Management Director",
        "Emergency Management Specialist",
        "Environmental Health Specialist",
        "Equal Opportunity Officer",
        "Extension Agent",
        "Field Organizer",
        "Foreign Service Officer",
        "Forest Ranger",
        "Fundraising Manager",
        "Government Affairs Director",
        "Government Contractor",
        "Health Inspector",
        "Housing Inspector",
        "Housing Manager",
        "Human Services Worker",
        "Legislative Analyst",
        "Legislative Assistant",
        "Librarian", // Also in Education
        "Mayor",
        "Member Services Representative (Non-Profit)",
        "Military Personnel (Various Ranks/Roles)",
        "Museum Director",
        "Non-Profit Administrator",
        "Non-Profit Executive Director",
        "Outreach Coordinator",
        "Park Manager",
        "Permit Technician",
        "Planning Technician",
        "Policy Advisor",
        "Policy Analyst",
        "Political Campaign Manager",
        "Political Consultant",
        "Postal Worker",
        "Program Assistant (Non-Profit)",
        "Program Manager (Non-Profit)",
        "Program Officer (Non-Profit)",
        "Public Administrator",
        "Public Affairs Specialist",
        "Public Health Nurse", // Also in Healthcare
        "Public Information Officer",
        "Public Works Director",
        "Recreation Leader",
        "Recycling Coordinator",
        "Sanitation Worker",
        "Social Services Director",
        "Social Worker",
        "State Park Ranger",
        "Town Clerk",
        "Town Planner",
        "Transportation Planner", // Also in Transport
        "Urban Planner", // Also in Engineering
        "Veteran Services Officer",
        "Volunteer Coordinator",
        "Water Quality Specialist",
        "Zoning Administrator",
        "Zoning Planner",

        // --- Agriculture, Animals & Environment ---
        "Agricultural Consultant",
        "Agricultural Economist",
        "Agricultural Engineer", // Also in Engineering
        "Agricultural Equipment Technician",
        "Agricultural Inspector", // Also in Gov
        "Agricultural Manager",
        "Agricultural Sales Representative",
        "Agricultural Scientist",
        "Agricultural Technician",
        "Animal Breeder",
        "Animal Caretaker",
        "Animal Control Officer",
        "Animal Nutritionist",
        "Animal Scientist", // Also in Science
        "Animal Shelter Manager",
        "Animal Trainer",
        "Apiarist (Beekeeper)",
        "Aquaculturist",
        "Arborist",
        "Conservation Scientist", // Also in Science
        "Crop Consultant",
        "Dairy Farmer",
        "Dog Walker",
        "Ecologist", // Also in Science
        "Environmental Compliance Specialist",
        "Environmental Educator",
        "Environmental Engineer", // Also in Engineering
        "Environmental Planner", // Also in Gov
        "Environmental Scientist", // Also in Science
        "Environmental Technician", // Also in Science
        "Farm Advisor",
        "Farm Equipment Operator",
        "Farm Laborer",
        "Farm Manager",
        "Farmer",
        "Field Technician (Agriculture)",
        "Fish & Game Warden",
        "Fisheries Biologist",
        "Forester", // Also in Science
        "Forestry Technician",
        "Greenhouse Manager",
        "Groundskeeper", // Also in Skilled Trades
        "Habitat Restoration Specialist",
        "Herd Manager",
        "Horse Trainer",
        "Horticulturalist", // Also in Science
        "Kennel Attendant",
        "Landscape Manager",
        "Livestock Manager",
        "Naturalist",
        "Nursery Manager",
        "Organic Farmer",
        "Pest Control Advisor",
        "Plant Breeder",
        "Poultry Farmer",
        "Rancher",
        "Soil Conservationist",
        "Stable Hand",
        "Sustainable Agriculture Specialist",
        "Veterinarian", // Also in Healthcare
        "Veterinary Assistant", // Also in Healthcare
        "Veterinary Technician", // Also in Healthcare
        "Vineyard Manager",
        "Water Conservationist",
        "Wildlife Biologist", // Also in Science
        "Wildlife Rehabilitator",
        "Winery Worker",
        "Zookeeper"
    ).distinct().sorted().toMutableList() // Ensure uniqueness and sort alphabetically
}