package com.example.buildairesume

object JobList {
    val jobList = mutableListOf(
        // Software & IT
        "Android Developer",
        "Android Designer",
        "Android Engineer",
        "Android UI/UX Designer",
        "iOS Developer",
        "iOS Engineer",
        "iOS UI/UX Designer",
        "Mobile App Developer",
        "Flutter Developer",
        "React Native Developer",
        "Software Engineer",
        "Software Developer",
        "Backend Developer",
        "Frontend Developer",
        "Full Stack Developer",
        "Web Developer",
        "Web Designer",
        "UI/UX Designer",
        "UI/UX Researcher",
        "Machine Learning Engineer",
        "Data Scientist",
        "AI Engineer",
        "Deep Learning Engineer",
        "Data Analyst",
        "Big Data Engineer",
        "Business Intelligence Analyst",
        "Cloud Engineer",
        "DevOps Engineer",
        "Site Reliability Engineer",
        "Cybersecurity Analyst",
        "Ethical Hacker",
        "Penetration Tester",
        "Blockchain Developer",
        "Smart Contract Developer",
        "Solidity Developer",
        "Embedded Systems Engineer",
        "IoT Developer",
        "Firmware Engineer",
        "System Administrator",
        "Network Engineer",
        "Database Administrator",
        "Game Developer",
        "Game Designer",
        "3D Animator",
        "VFX Artist",
        "Quality Assurance Engineer",
        "Automation Tester",
        "Manual Tester",
        "Technical Support Engineer",
        "Technical Writer",
        "IT Consultant",

        // Engineering & Architecture
        "Mechanical Engineer",
        "Electrical Engineer",
        "Civil Engineer",
        "Structural Engineer",
        "Architect",
        "Interior Designer",
        "Industrial Designer",
        "Landscape Architect",
        "Construction Manager",
        "Urban Planner",
        "Surveyor",
        "Geotechnical Engineer",

        // Business & Management
        "Product Manager",
        "Project Manager",
        "Scrum Master",
        "Business Analyst",
        "Operations Manager",
        "Supply Chain Manager",
        "Marketing Manager",
        "Sales Manager",
        "Account Manager",
        "Brand Manager",
        "Finance Manager",
        "Investment Analyst",
        "Risk Manager",
        "Compliance Officer",
        "Chief Executive Officer (CEO)",
        "Chief Technology Officer (CTO)",
        "Chief Financial Officer (CFO)",
        "Business Development Manager",
        "Strategy Consultant",
        "Public Relations Manager",

        // HR (Human Resources) Roles
        "HR Manager",
        "HR Business Partner",
        "HR Generalist",
        "HR Specialist",
        "HR Coordinator",
        "HR Director",
        "HR Consultant",
        "HR Administrator",
        "Talent Acquisition Specialist",
        "Recruitment Specialist",
        "Technical Recruiter",
        "Corporate Recruiter",
        "Executive Recruiter",
        "Sourcing Specialist",
        "Employee Relations Specialist",
        "Diversity & Inclusion Manager",
        "Compensation & Benefits Manager",
        "Payroll Specialist",
        "Training & Development Manager",
        "Learning & Development Coordinator",
        "HR Compliance Manager",
        "Workforce Planning Analyst",
        "HRIS Analyst (Human Resources Information Systems Analyst)",
        "Organizational Development Consultant",
        "Performance Management Specialist",

        // Finance & Accounting
        "Chartered Accountant",
        "Financial Analyst",
        "Auditor",
        "Tax Consultant",
        "Investment Banker",
        "Stockbroker",
        "Actuary",
        "Economist",

        // Healthcare & Medicine
        "Doctor",
        "Surgeon",
        "Dentist",
        "Orthopedic Surgeon",
        "Pediatrician",
        "Psychiatrist",
        "Psychologist",
        "Nurse",
        "Physiotherapist",
        "Pharmacist",
        "Veterinarian",
        "Medical Researcher",
        "Radiologist",
        "Lab Technician",
        "Optometrist",
        "Nutritionist",
        "Dietitian",

        // Education & Research
        "Professor",
        "Lecturer",
        "School Teacher",
        "Education Consultant",
        "Librarian",
        "Curriculum Developer",
        "Research Scientist",
        "Instructional Designer",
        "Academic Advisor",
        "Language Translator",

        // Legal & Law Enforcement
        "Lawyer",
        "Judge",
        "Legal Consultant",
        "Paralegal",
        "Police Officer",
        "Detective",
        "Forensic Scientist",
        "Security Consultant",
        "Cybercrime Investigator",

        // Media, Design & Arts
        "Graphic Designer",
        "Motion Graphics Designer",
        "Video Editor",
        "Photographer",
        "Illustrator",
        "Fashion Designer",
        "Textile Designer",
        "Journalist",
        "Editor",
        "Copywriter",
        "Content Creator",
        "Social Media Manager",
        "Public Relations Specialist",
        "Musician",
        "Composer",
        "Actor",
        "Film Director",
        "Screenwriter",

        // Hospitality & Tourism
        "Hotel Manager",
        "Event Planner",
        "Travel Agent",
        "Tour Guide",
        "Chef",
        "Bartender",
        "Restaurant Manager"
    )


}