package com.example.buildairesume

object SkillsList {
    val skillsList = mutableListOf(
        // **Basic Technical Skills**
        "HTML",
        "CSS",
        "Responsive Web Design",
        "Flexbox",
        "CSS Grid",
        "Version Control",
        "Git",
        "GitHub",
        "GitLab",
        "Bitbucket",
        "Command Line Basics",
        "Terminal Navigation",
        "Bash Scripting",
        "Shell Scripting",
        "PowerShell",
        "Regular Expressions",
        "Markdown",
        "LaTeX",

        // **Programming Languages**
        "Kotlin",
        "Java",
        "Python",
        "JavaScript",
        "TypeScript",
        "Swift",
        "Dart",
        "C",
        "C++",
        "C#",
        "Go",
        "Rust",
        "PHP",
        "R",
        "Ruby",
        "Perl",
        "Scala",
        "Objective-C",
        "Verilog HDL",
        "VHDL",
        "Assembly Language",
        "MATLAB",
        "Fortran",
        "COBOL",
        "Ada",
        "F#",
        "Prolog",
        "Lisp",
        "Haskell",
        "Scheme",
        "Elixir",
        "Racket",
        "OCaml",
        "Julia",
        "Tcl",
        "Forth",

        // **Frontend Development**
        "React.js",
        "Vue.js",
        "Angular",
        "Svelte",
        "Next.js",
        "Nuxt.js",
        "Bootstrap",
        "Tailwind CSS",
        "SASS",
        "LESS",
        "WebSockets",
        "WebAssembly",
        "PWA (Progressive Web Apps)",
        "Three.js",
        "Babylon.js",
        "Canvas API",
        "WebGL",
        "Figma to Code",
        "Adobe XD to Code",

        // **Backend Development**
        "Node.js",
        "Express.js",
        "Django",
        "Flask",
        "FastAPI",
        "Spring Boot",
        "Laravel",
        "GraphQL",
        "REST APIs",
        "gRPC",
        "RPC",
        "Microservices Architecture",
        "NestJS",
        "ASP.NET Core",
        "Hapi.js",
        "Koa.js",
        "Phoenix Framework",

        // **Mobile Development**
        "Android Development",
        "Android SDK",
        "Jetpack Compose",
        "XML UI Design",
        "iOS Development",
        "SwiftUI",
        "Flutter",
        "React Native",
        "Xamarin",
        "Cordova",
        "KMM (Kotlin Multiplatform Mobile)",
        "Capacitor.js",
        "Unity for Mobile",

        // **Database Management**
        "SQL",
        "MySQL",
        "PostgreSQL",
        "MongoDB",
        "Firebase Firestore",
        "DynamoDB",
        "Cassandra",
        "Redis",
        "Elasticsearch",
        "Graph Databases",
        "Neo4j",
        "Data Warehousing",
        "ClickHouse",
        "CockroachDB",
        "Apache HBase",
        "MariaDB",

        // **Cloud & DevOps**
        "AWS",
        "Google Cloud Platform (GCP)",
        "Microsoft Azure",
        "Cloud Computing",
        "Serverless Computing",
        "Docker",
        "Kubernetes",
        "Terraform",
        "CI/CD Pipelines",
        "Jenkins",
        "GitHub Actions",
        "Ansible",
        "Puppet",
        "Chef",
        "CloudFormation",
        "Helm",
        "OpenShift",
        "Azure DevOps",
        "Istio",

        // **Cybersecurity**
        "Ethical Hacking",
        "Penetration Testing",
        "Network Security",
        "Cloud Security",
        "Cryptography",
        "Security Information and Event Management (SIEM)",
        "Threat Intelligence",
        "Incident Response",
        "Identity & Access Management (IAM)",
        "Reverse Engineering",
        "Forensics Analysis",
        "Malware Analysis",
        "Zero Trust Architecture",

        // **Machine Learning & AI**
        "TensorFlow",
        "PyTorch",
        "Keras",
        "Scikit-learn",
        "Pandas",
        "NumPy",
        "Natural Language Processing (NLP)",
        "Computer Vision",
        "Reinforcement Learning",
        "Generative AI",
        "LLM Fine-tuning",
        "AutoML",
        "Edge AI",
        "MLOps",
        "Hugging Face Transformers",
        "ONNX",
        "Model Quantization",

        // **Engineering Fields**
        "Mechanical Engineering",
        "Electrical Engineering",
        "Civil Engineering",
        "Aerospace Engineering",
        "Chemical Engineering",
        "Biotechnology",
        "Automobile Engineering",
        "Marine Engineering",
        "Mechatronics",
        "Robotics Engineering",
        "Biomedical Engineering",
        "Structural Engineering",
        "Thermodynamics",
        "Fluid Mechanics",
        "HVAC Systems",
        "Control Systems",
        "Power Systems",

        // **Software & Tools**
        "AutoCAD",
        "SolidWorks",
        "ANSYS",
        "CATIA",
        "Fusion 360",
        "NX CAD",
        "Creo Parametric",
        "MATLAB Simulink",
        "LTspice",
        "Cadence Virtuoso",
        "OrCAD",
        "Multisim",
        "KiCad",
        "Proteus",
        "ETAP",
        "PSCAD",
        "LabVIEW",
        "HyperMesh",
        "Abaqus",
        "COMSOL Multiphysics",
        "MSC Nastran",
        "PTC Windchill",
        "OptiStruct",
        "FLUENT CFD",
        "OpenFOAM",

        // **Embedded Systems & IoT**
        "Verilog",
        "VHDL",
        "SystemVerilog",
        "SPICE",
        "Assembly (x86, ARM, MIPS)",
        "Embedded C",
        "Keil uVision",
        "PIC Programming",
        "AVR Programming",
        "8051 Microcontroller",
        "FPGA Programming",
        "Xilinx Vivado",
        "Quartus Prime",
        "Embedded Linux",
        "RTOS (Real-Time Operating Systems)",
        "IoT Protocols",
        "MQTT",
        "Zigbee",
        "LoRaWAN",
        "Home Automation",
        "CAN Bus",
        "Modbus",

        // **Emerging Technologies**
        "Blockchain Development",
        "Smart Contracts",
        "Solidity",
        "Quantum Computing",
        "IoT Development",
        "3D Printing",
        "Game Development",
        "AR/VR Development",
        "Metaverse Technologies",
        "Digital Twins",
        "Edge Computing",
        "5G Technologies",
        "AI Ethics",
        "Cyber-Physical Systems",

        // **Soft Skills**
        "Leadership",
        "Communication",
        "Problem-Solving",
        "Critical Thinking",
        "Time Management",
        "Adaptability",
        "Teamwork",
        "Emotional Intelligence",
        "Negotiation",
        "Public Speaking",
        "Conflict Resolution",
        "Creativity",
        "Collaboration",
        "Growth Mindset",
        "Decision Making",

        // **Other Professions**
        "Law & Legal Research",
        "Journalism",
        "Teaching & Pedagogy",
        "Psychology & Counseling",
        "Event Planning",
        "Hospitality Management",
        "Culinary Arts",
        "Architecture",
        "Urban Planning",

        // **Miscellaneous Software**
        "SPSS",
        "STATA",
        "SAS",
        "EViews",
        "GIMP",
        "CorelDRAW",
        "Affinity Designer",
        "AutoDesk Revit",
        "SketchUp",
        "ZBrush",
        "Houdini",
        "Figma",
        "Blender",

        // **Additional Skills**
        "SAP",
        "Oracle ERP",
        "Salesforce",
        "SAP FICO",
        "SAP MM",
        "SAP SD",
        "Tableau",
        "Power BI",
        "QlikView",
        "Looker",
        "Snowflake",
        "BigQuery",
        "Data Lakes",
        "Apache Kafka",
        "Unity 3D",
        "Unreal Engine",
        "Cocos2d-x",
        "Game AI",
        "WebRTC",
        "WebSockets",
        "GraphQL Subscriptions",
        "Web Development",
        "DSA",
        "DBMS",
        "Data Analytics",
        "Data Visualization",
        "Embedded C Programming"
    )
}
